### ISSUE TITLE
Dual for shutters

### ISSUE THREAD

**Issue by kiralikbeyin** [maximkulkin/esp-homekit-demo#100]
How to make relay off after xx seconds?So it can control motors like roller shutter.

@maximkulkin Can you add a variable (xx seconds) to config setup under ssid and password.
if 0 seconds normal mode no auto-off else relay will be off after xx seconds?

I am new for opensdk.. Thanks

**Comment by kiralikbeyin** [comment]
Please anyone confirm dual example works well?

**Comment by maximkulkin** [comment]
As I said before, we try to keep *examples* less cluttered so people can understand what's going on. they are not meant to be one-fits-all solution.
