### ISSUE TITLE
WebUpdate

### ISSUE THREAD

**Issue by kiralikbeyin** [maximkulkin/esp-homekit-demo#101]
iOS will publish new things so how can we update it 1 year later?

WebUpdate like Arduino IDE can solve this... https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WebServer/examples/WebUpdate/WebUpdate.ino

Any plan?

**Comment by maximkulkin** [comment]
1. Updates to HomeKit are backward compatible, so you do not need to update your accessory firmware with a new release of iOS.
2. Mostly protocol have not changed so far, it's only addition of new accessory types/services/characteristics. Most(all?) existing services and characteristics are already present in esp-homekit framework, but if you will need a custom one (or new one support for which was not added yet), you should be able to configure it manually by specifying all service/characteristics parameters.
3. You can upgrade your accessory same way as initially - over the wire. If you want an OTA upgrade, there is a work going on at https://github.com/HomeACcessoryKid/life-cycle-manager
