### ISSUE TITLE
Relay auto off

### ISSUE THREAD

**Issue by kiralikbeyin** [maximkulkin/esp-homekit-demo#106]
How can i make relay off after xx seconds?

**Comment by renssies** [comment]
I think most people will solve this using automations in the Home app, when X turns on, turn off after x seconds

**Comment by renssies** [comment]
I think most people will solve this using automations in the Home app, when X turns on, turn off after x seconds

**Comment by supersjimmie** [comment]
I guess you can just create a task with ```xTaskCreate``` that waits xx seconds with ```vTaskDelay``` and then turns off the relay (by setting the ```relay.value.bool_value``` to ```false``` and calling ```homekit_characteristic_notify```).
