### ISSUE TITLE
Esp32 vs esp8266 response time?

### ISSUE THREAD

**Issue by jukorp** [maximkulkin/esp-homekit-demo#109]
What is the response time? 
I want a quick response.
If I press the button ”e.g. 4ch exmple”. when does the other homekit device react? e.g. lamp.

**Comment by maximkulkin** [comment]
I'm using a floor lamp enhanced with ESP8266 smartness. Turning them on and off is almost instant. However, when you open Home app it takes some time to query those devices. Establishing connection usually takes a few seconds on ESP8266. With ESP32 it's fraction of a second.
