### ISSUE TITLE
Error reading data from socket (code 113)

### ISSUE THREAD

**Issue by konifer44** [maximkulkin/esp-homekit-demo#114]
What does that error mean? Im using Sonoff switch app. It occurs about 30-60min after program start. 

Edit:: This error occurs also in Esp32/Led app. After few minutes iOS says "no response"

```
I (143392) wifi: n:11 0, o:11 2, ap:255 255, sta:11 2, prof:1
!!! HomeKit: [Client 55] Error reading data from socket (code 113). Disconnecting
STA disconnected
>>> HomeKit: [Client 55] Closing client connection
```

**Comment by kosukekurimoto** [comment]
I am experiencing the same problem.
```
!!! HomeKit: [Client 58] Error reading data from socket (code 113). Disconnecting
>>> HomeKit: [Client 58] Closing client connection
!!! HomeKit: [Client 60] Error reading data from socket (code 113). Disconnecting
>>> HomeKit: [Client 60] Closing client connection
>>> HomeKit: [Client 59] Closing client connection
```

**Comment by LiangyongFShen** [comment]
@kosukekurimoto I have the same problem, have you solved it？

**Comment by maximkulkin** [comment]
Is some functionality broken or you are just concerned about message in the log?

**Comment by pbendersky** [comment]
I think this is what was happening when using `lwip` sockets. You solved a few weeks ago in the main library.

**Comment by konifer44** [comment]
Seems to be fine now. Closing
