### ISSUE TITLE
Display for thermostat

### ISSUE THREAD

**Issue by Kristian8606** [maximkulkin/esp-homekit-demo#115]
Thanks to RavenSystem, who wrote a code for me, now I have a thermostat with temperature control buttons.
I would like to add a display, but I'm not familiar with the firmware.
It is easier for me to connect  esp display to an arduino environment and then read the temperature using the RX TX.
The question is how to print the ESP HomeKit thermostat values in UART and read them from another esp?

Excuse me for my bad English

**Comment by konifer44** [comment]
Hey, sorry for asking here. Do you have problem with “no response” few minutes after start app?

**Comment by Kristian8606** [comment]
I have a problem with the thermostat of maximkulkin and right now I use this one 
https://github.com/RavenSystem/esp-homekit-devices/tree/master/devices_legacy/Sonoff_TH 
Option button -> https://github.com/Kristian8606/Sonoff_TH

**Comment by Kristian8606** [comment]
I was able to make a serial connection between the homekit thermostat and the esp and send the display data

Can I send data via serial link from esp to home thermostat.
