### ISSUE TITLE
esp8266 video camera example?

### ISSUE THREAD

**Issue by bryantcoles** [maximkulkin/esp-homekit-demo#116]
I have Multiple esp’s up and running with the great work here. Does anyone know if it’s possible to add a camera module to a NodeMCU board? If so does anyone have an example?

**Comment by idumzaes** [comment]
You will most likely be better off using a RPi for that.

**Comment by maximkulkin** [comment]
I would usually agree, but recently I found [this device](https://www.amazon.com/gp/product/B07DVD4J7N) and I can't wait to give it a try.

**Comment by idumzaes** [comment]
that looks rather interesting but I'm fairly sure the framerate will be abysmal.

**Comment by maximkulkin** [comment]
The work is happening in this repository: https://github.com/maximkulkin/esp32-homekit-camera
