### ISSUE TITLE
2 Channel Sonoff?

### ISSUE THREAD

**Issue by murathanaraz** [maximkulkin/esp-homekit-demo#122]
Hello, I have a two channel sonoff device. Does this firmware works with my device as well?
thank you

**Comment by royfocker19** [comment]
https://github.com/maximkulkin/esp-homekit-demo/tree/master/examples/sonoff_dual_lights

https://github.com/lzparkma/esp-homekit-demo/tree/master/examples/sonoff_dual_toggle
