### ISSUE TITLE
Unable to compile example

### ISSUE THREAD

**Issue by bwicks** [maximkulkin/esp-homekit-demo#123]
Hi there, 
I'm trying to compile the LED example having followed instructions however I get the below message:
make: Entering directory '/home/billy/Documents/esp-homekit-demo/examples/led'
Makefile:13: /common.mk: No such file or directory
make: *** No rule to make target '/common.mk'. Stop.
make: Leaving directory '/home/billy/Documents/esp-homekit-demo/examples/led'
Could you please advise?

Thank you.

**Comment by bwicks** [comment]
I have logged out and back in having changed the environment variables and I now see this error:
'/home/billy/Documents/esp-homekit-demo/examples/led'
CC /home/billy/Documents/esp-open-rtos/open_esplibs/libmain/user_interface.c
make: xtensa-lx106-elf-gcc: Command not found
/home/billy/Documents/esp-open-rtos/open_esplibs/component.mk:15: recipe for target 'build/open_esplibs_libmain//user_interface.o' failed
make: *** [build/open_esplibs_libmain//user_interface.o] Error 127
make: Leaving directory '/home/billy/Documents/esp-homekit-demo/examples/led'

**Comment by bwicks** [comment]
Nevermind, solved it myself :)

**Comment by maximkulkin** [comment]
@bwicks What was the issue?

**Comment by bwicks** [comment]
I had set them but I was silly and didn't restart for the changes to take effect :/

**Comment by orisraeli** [comment]
I'm stuck with this errors too.
Sorry for being a noob but how do i set these env variables?

**Comment by maccoylton** [comment]
if you want to do this from the command line on Mac OS then here's what I use, you may need to change some of the lines depending on where you installed stuff 

export PATH="/volumes/case-sensitive/esp-open-sdk/xtensa-lx106-elf/bin:/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
export BIN_PATH=/volumes/case-sensitive/esp-open-sdk/ESP8266_RTOS_SDK/bin
export SDK_PATH=/volumes/case-sensitive/esp-open-sdk/esp-open-rtos
export ESPPORT=/dev/cu.usbserial

**Comment by orisraeli** [comment]
Thanks,
And if I'm using Ubuntu, the commands are the same?

**Comment by peros550** [comment]
In Ubuntu, I created a folder called "projects" which resides into my user's home folder. Inside that folder I cloned esp-homekit-demo. Here are the commands for setting the variables:

export SDK_PATH=~/projects/esp-open-rtos
export ESPPORT=/dev/ttyUSB0

Pay attention to the last command. Although the Serial port in macOS is defined as "cu.usbserial" , in Ubuntu is different (ttyUSB0). And if that still does not work, you might need to check which number was assigned to your device upon connecting it to your PC.

**Comment by 4Xsample** [comment]
And in raspbian what should be¿?
The same as Ubuntu¿?

**Comment by maximkulkin** [comment]
@4Xsample that depends on different things (e.g. which linux kernel it is running, which usb-to-serial chip is installed on your devboard or which usb-to-serial adapter you use). A general suggestion would be to first look for /dev/tty* devices, then figuring out what new device appears after you connect esp8266. If /dev/tty* does not work, you can try using /dev/cu.*

**Comment by 4Xsample** [comment]
Is a raspberry b3+
pi@RasPro:~/ESP8266/esp-homekit-demo $ uname -r
4.14.98-v7+
The usb port is on /dev/ttyUSB0 (is where I have the arduino program configured to write the same board)

**Comment by greensouth** [comment]
anyone having this? /Volumes/open-rtos-volume/esp-open-rtos/common.mk:217: *** multiple target patterns.  Stop.

**Comment by maximkulkin** [comment]
@greensouth what were you trying to do?

**Comment by greensouth** [comment]
Forget about it @maximkulkin, I'm working on a shared Dropbox folder from home and the office, and it just didn't like that.

Moving to an independent folder and worked like a charm.

**Comment by hfosteriv** [comment]
lost my Debian virtual machine (don't ask), and now I can't get it to build for some reason. I keep trying to set the path correctly, but I'm still getting the 'missing common.mk' error. Any ideas?

**Comment by maximkulkin** [comment]
@hfosteriv create another virtual machine, use docker, it shouldn't be hard.

**Comment by okanduzyel** [comment]
I am using macOS operation system. I installed correctly vagrant and did step by step instructions but I have same issue as this topic. 

First, my usb devices have connected and was founded by system:

T:  Bus=02 Lev=01 Prnt=01 Port=00 Cnt=01 Dev#=  2 Spd=12  MxCh= 0
D:  Ver= 1.10 Cls=ff(vend.) Sub=00 Prot=00 MxPS= 8 #Cfgs=  1
P:  Vendor=1a86 ProdID=7523 Rev=02.54
S:  Product=USB2.0-Serial
C:  #Ifs= 1 Cfg#= 1 Atr=80 MxPwr=96mA
I:  If#= 0 Alt= 0 #EPs= 3 Cls=ff(vend.) Sub=01 Prot=02 Driver=ch341

and my error is that:

vagrant@vagrant:~/esp-homekit-demo$ make -C examples/led test
make: Entering directory '/home/vagrant/esp-homekit-demo/examples/led'
CC /home/vagrant/esp-open-rtos/open_esplibs/libmain/user_interface.c
make: xtensa-lx106-elf-gcc: Command not found
/home/vagrant/esp-open-rtos/open_esplibs/component.mk:15: recipe for target 'build/open_esplibs_libmain//user_interface.o' failed
make: *** [build/open_esplibs_libmain//user_interface.o] Error 127
make: Leaving directory '/home/vagrant/esp-homekit-demo/examples/led'

What should I do to solve that problem? Can you explain step by step with supporting codes? I am new at terminal codes, linux and all.

**Comment by MizzyAntunes** [comment]
> I am using macOS operation system. I installed correctly vagrant and did step by step your instructions on YouTube but I have got same issue as this topic.
> 
> First, my usb devices have connected and was founded by system:
> 
> T: Bus=02 Lev=01 Prnt=01 Port=00 Cnt=01 Dev#= 2 Spd=12 MxCh= 0
> D: Ver= 1.10 Cls=ff(vend.) Sub=00 Prot=00 MxPS= 8 #Cfgs= 1
> P: Vendor=1a86 ProdID=7523 Rev=02.54
> S: Product=USB2.0-Serial
> C: #Ifs= 1 Cfg#= 1 Atr=80 MxPwr=96mA
> I: If#= 0 Alt= 0 #EPs= 3 Cls=ff(vend.) Sub=01 Prot=02 Driver=ch341
> 
> and my error is that:
> 
> vagrant@vagrant:~/esp-homekit-demo$ make -C examples/led test
> make: Entering directory '/home/vagrant/esp-homekit-demo/examples/led'
> CC /home/vagrant/esp-open-rtos/open_esplibs/libmain/user_interface.c
> make: xtensa-lx106-elf-gcc: Command not found
> /home/vagrant/esp-open-rtos/open_esplibs/component.mk:15: recipe for target 'build/open_esplibs_libmain//user_interface.o' failed
> make: *** [build/open_esplibs_libmain//user_interface.o] Error 127
> make: Leaving directory '/home/vagrant/esp-homekit-demo/examples/led'
> 
> What should I do to solve that problem? Can you explain step by step with supporting codes? I am new at terminal codes, linux and all.

I'm almost with the same error 

vagrant@vagrant-ubuntu-trusty-64:~/esp-homekit-demo$ make -C examples/led test
make: Entering directory `/home/vagrant/esp-homekit-demo/examples/led'
CC /home/vagrant/esp-open-rtos/open_esplibs/libmain/ets_timer.c
make: xtensa-lx106-elf-gcc: Command not found
make: *** [build/open_esplibs_libmain//ets_timer.o] Error 127
make: Leaving directory `/home/vagrant/esp-homekit-demo/examples/led'

Please, somebody help us

**Comment by maximkulkin** [comment]
You do not have SDK properly installed

**Comment by MizzyAntunes** [comment]
> You do not have SDK properly installed

Sorry, I am noob and I don't understand, what should I do to correct?

**Comment by maximkulkin** [comment]
You need to install xtensa toolchain first. I do not know what OS you're running, but I recommend using docker. I've built a toolchain image which is available from hub.docker.com:

    docker pull maximkulkin/esp-rtos
    docker tag maximkulkin/esp-rtos esp-rtos
    docker run -it --rm -v "$(pwd):/project" -w /project esp-rtos make -C examples/led all

**Comment by MizzyAntunes** [comment]
> You need to install xtensa toolchain first. I do not know what OS you're running, but I recommend using docker. I've built a toolchain image which is available from hub.docker.com:
> 
> ```
> docker pull maximkulkin/esp-rtos
> docker tag maximkulkin/esp-rtos esp-rtos
> docker run -it --rm -v "$(pwd):/project" -w /project esp-rtos make -C examples/led all
> ```

Ok, tks

**Comment by jpasqua** [comment]
> Forget about it @maximkulkin, I'm working on a shared Dropbox folder from home and the office, and it just didn't like that.
> 
> Moving to an independent folder and worked like a charm.

@greensouth: Did you ever figure out why working in a Dropbox folder caused problems? I have that issue too and like you, resolved it by moving the files elsewhere.

**Comment by christiankoback** [comment]
so... I have everything set up but...   when I run the command "make -C examples/led all".  I get:

make: *** No rule to make target `all'.  Stop.

any ideas as to this?     I am expecting to get the .bin files created with this command.
