### ISSUE TITLE
i cahnged the env variables to 1mb chip did the flashing and now iam have a 4 mb chip and after flashing the device is not working seems an error in flas base address 

### ISSUE THREAD

**Issue by surya31** [maximkulkin/esp-homekit-demo#125]
whasts the base addres for homekit 4mb chip ??

**Comment by dezdeepblue** [comment]
you need to remove the environment variable used only for 1MB flash chips. Although I'm not sure if the problem is about the flash size
`unset HOMEKIT_SPI_FLASH_BASE_ADDR`

**Comment by surya31** [comment]
yes it helped.. but still fiquring  out real solution

**Comment by maximkulkin** [comment]
Why do you think that wasn't a "real solution" and what do you expect from a real one?
