### ISSUE TITLE
Can create video tutorial?

### ISSUE THREAD

**Issue by lorenzorobbi** [maximkulkin/esp-homekit-demo#127]
i can't understand all part of the instruction.
Can anybody create an illustration video?
Thanks, and sorry for my bad english

**Comment by slozano95** [comment]
check this out https://github.com/OtakuDigitChoc/esp-homekit-demo-stepByStep

**Comment by dachoeks3** [comment]
If I have time next week I might do it.

**Comment by lorenzorobbi** [comment]
@dachoeks3, wait for it.
@slozano95 Thanks so much
