### ISSUE TITLE
Add pwm dimmer?

### ISSUE THREAD

**Issue by jukorp** [maximkulkin/esp-homekit-demo#128]
can you help me?
I need pwm dimmer. ”One color led strip”

-One button. ”Long press to dimming and short press on/off”
-Initial state is off.
-Remember dimmable settings.

**Comment by jukorp** [comment]
I would like to use esp32.

**Comment by SkyManager** [comment]
+1 for "Add pwm dimmer")

**Comment by outsiderz** [comment]
+

**Comment by maximkulkin** [comment]
There is a [PWM dimmer example](https://github.com/maximkulkin/esp-homekit-demo/tree/master/examples/sonoff_basic_pwm) already
