### ISSUE TITLE
esp won't connect to wifi after restarting it (wifi_config example)

### ISSUE THREAD

**Issue by buschco** [maximkulkin/esp-homekit-demo#130]
### Problem
Connecting to WIFI, pairing to HomeKit and controlling the LED works fine but **after disconnecting the ESP from the power it will not connect to the previously configured WIFI.**
### Attempts
I tried two different WIFI networks and two different ESP-8266 (the small one with 8 pins).
### Logs
I was not able to get the anything from the ESP. Probably my 8-Pin ESP to USB converter does not support debugging.

**Comment by maccoylton** [comment]
if you can flash, you should be able to us the same connection to see the trace .. did you compile with debugging turned on in the Makefile?

**Comment by buschco** [comment]
I was able to get logs now. It seems after restarting the ESP it would stop working.
`Opening /dev/tty.wchusbserial1430 at 115200bps...` then nothing. I think this issue is a duplicate of #124

**Comment by hampusiggstrom** [comment]
I got the same problem seems to be related to the 8 pin version of ESP8622-01. ESP-12F works just fine for me.

**Comment by hfosteriv** [comment]
Check out my related issue/discussion I just posted, I am thinking this is hardware difference related. Issue #171

**Comment by maximkulkin** [comment]
Please check documentation on your board, it might be that you need to pull some pin high/low to force it loading program instead of bootloader after power reset.
