### ISSUE TITLE
Библиотка HomeKit-ESP для Arduino IDE

### ISSUE THREAD

**Issue by alxnovo** [maximkulkin/esp-homekit-demo#131]
@maximkulkin а существуют библиотеки HomeKit для Ардуино IDE, чтобы не мучаться со сборкой?

**Comment by maximkulkin** [comment]
К сожалению, не существуют.

**Comment by alxnovo** [comment]
Максим, а как считаете возможно написать такую библиотеку на основе того SDK который вы используете для компиляции своей прошивки и если да, то можете ли её создать или кто-то другой?

**Comment by maximkulkin** [comment]
Мне недавно стало известно о другом проекте - реализации HomeKit для ESP32 с Arduino SDK - https://github.com/An00bIS47/Homekit. Если интересно, можете поинтересоваться там. В мои планы интеграция с Arduino SDK не входит.
