### ISSUE TITLE
Led_Strip change RGB to GRB 

### ISSUE THREAD

**Issue by k5beason** [maximkulkin/esp-homekit-demo#134]
How do I change the color from RGB to GRB. The Colors on my rgb strip are swapped. Thus currently Red is Green and Green is Red.

**Comment by maximkulkin** [comment]
Since you did not mention what setup you have, I assume you're using variation of led_strip example code. If so, all you need to do is swap R and G components of color when you send it to LEDs (at https://github.com/maximkulkin/esp-homekit-demo/blob/master/examples/led_strip/led_strip.c#L77):
```c
void led_string_fill(ws2812_pixel_t rgb) {
    int x = rgb.red;
    rgb.red = rgb.green;
    rgb.green = x;

    // ... rest of code
}
```
