### ISSUE TITLE
I would like to add a button so that you can manage both from the phone and from the button press on ESP

### ISSUE THREAD

**Issue by Deymon112** [maximkulkin/esp-homekit-demo#139]
I would like to add a button so that you can manage both from the phone and from the button press on ESP

**Comment by idumzaes** [comment]
check out my fork right here https://github.com/idumzaes/esp-homekit-demo

**Comment by Kristian8606** [comment]
The problem with updating the button in the app is fixed https://github.com/Kristian8606/LED_Strip
