### ISSUE TITLE
Add Amazon Alexa to esp8266/32

### ISSUE THREAD

**Issue by dachoeks3** [maximkulkin/esp-homekit-demo#141]
Would it be possible to add Alexa controls in conjunction with Apple HomeKit? I have tried to search for examples on RTOS and Amazon Alexa but couldn't find anything.

**Comment by b0rv3g4r4** [comment]
Im interested too

**Comment by NorthernMan54** [comment]
I’m the developer of the homebridge-alexa skill, and would gladly work on this with someone.

Having esp-HomeKit participate with my skill, should be straight forward as it just uses the HAP API without encryption/pairing.  If you have the homebridge-alexa skill installed on your local network, and your esp-HomeKit device was visible without encryption it should just work.

**Comment by tomasrocchetti** [comment]
I'm interested too. I tried homebridge-alexa but it doesn't discover my esp-HomeKit devices

**Comment by maximkulkin** [comment]
Closing this as support for Alexa is outside of this project scope
