### ISSUE TITLE
help to understand project...

### ISSUE THREAD

**Issue by lesgobbi** [maximkulkin/esp-homekit-demo#142]
**part 1:**
I would like to control 4 relays in a totally offline and independent way only using wall switches (something like pull-up) and controlling global status variables notifying you when you have a connection

**part 2:**
I would like to control these 4 relays using the homekit synchronized with the status of the wall switches, ie if I connected a relay using the iphone, when changing the switch state from wall to state should change, notify and change the state in the home app of the iphone.

**part 3:**
in a specific case, two of the relays must function inversely in relation to one another, having both states: 

- R1_off and R2_off
- R1_on and  R2_off
- R1_off and  R2_on

### **What I have achieved so far:**
using the LED example I managed to make the iphone control the 4 relays, but I could not integrate with the wall switches.

with the example of sonoff_dual_lights I advanced something, but I'm confused, the toggle function makes a damn mess instead of working as expected it would work ...

Thank you very much, this project has helped me a lot!

**Comment by maximkulkin** [comment]
Thing is that you need to use your switches as logical signals to controller (ESP8266) to know that the state should be changed. To implement that, you need to connect those switches to particular pin and ground, enable pull up on that pin and react on level change from 0 -> 1 and 1 -> 0. Same technique is used in 
https://github.com/maximkulkin/esp-homekit-demo/tree/master/examples/sonoff_dual_lights
