### ISSUE TITLE
help OLED

### ISSUE THREAD

**Issue by Kristian8606** [maximkulkin/esp-homekit-demo#143]
I'm trying to merge the thermostat code with the ssd1306 display
 please help.

> /*
 * Thermostat example
 *
 * Wiring is as follows (requires ESP-12 as it needs 4 GPIOs):
 *
 * DHT11 (temperature sensor)
 *
 *               -------------
 *              |GND       VCC|    (These go to control pins of relay)
 *              |15         13| --> Heater
 *              |2          12| --> Cooler
 *              |0          14| --> Fan
 *              |5          16|
 * DHT Data <-- |4       CH_PD|
 *              |RXD       ADC|
 *              |TXD      REST|
 *               -------------
 *              |   |-| |-| | |
 *              | __| |_| |_| |
 *               -------------
 *
 */
 #include <espressif/esp_common.h>
#include <queue.h>
#include <timers.h>
#include <string.h>
#include <ssd1306/ssd1306.h>
#include <stdio.h>
#include <espressif/esp_wifi.h>
#include <espressif/esp_sta.h>
#include <espressif/esp_system.h>
#include <esp/uart.h>
#include <esp8266.h>
#include <etstimer.h>
#include <esplibs/libmain.h>
#include <FreeRTOS.h>
#include <task.h>

#include <homekit/homekit.h>
#include <homekit/characteristics.h>
#include "wifi.h"

#include <dht/dht.h>

#define LED_PIN 2
#define TEMPERATURE_SENSOR_PIN 4
#define FAN_PIN 14
#define COOLER_PIN 12
#define HEATER_PIN 13
#define TEMPERATURE_POLL_PERIOD 10000
#define HEATER_FAN_DELAY 30000
#define COOLER_FAN_DELAY 0

#define LOAD_ICON_X 54
#define LOAD_ICON_Y 42
#define LOAD_ICON_SIZE 20

#define CIRCLE_COUNT_ICON_X 100
#define CIRCLE_COUNT_ICON_Y 52

/* Remove this line if your display connected by SPI */
#define I2C_CONNECTION

#ifdef I2C_CONNECTION
    #include <i2c/i2c.h>
#endif
#include "fonts/fonts.h"

/* Change this according to you schematics and display size */
#define DISPLAY_WIDTH  128
#define DISPLAY_HEIGHT 64

#ifdef I2C_CONNECTION
    #define PROTOCOL SSD1306_PROTO_I2C
    #define ADDR     SSD1306_I2C_ADDR_0
    #define I2C_BUS  0
    #define SCL_PIN  5
    #define SDA_PIN  4
#else
    #define PROTOCOL SSD1306_PROTO_SPI4
    #define CS_PIN   5
    #define DC_PIN   4
#endif

#define DEFAULT_FONT FONT_FACE_TERMINUS_6X12_ISO8859_1

/* Declare device descriptor */
static const ssd1306_t dev = {
    .protocol = PROTOCOL,
#ifdef I2C_CONNECTION
.i2c_dev.bus      = I2C_BUS,
.i2c_dev.addr     = ADDR,
#else
    .cs_pin   = CS_PIN,
    .dc_pin   = DC_PIN,
#endif
    .width    = DISPLAY_WIDTH,
    .height   = DISPLAY_HEIGHT
};

/* Local frame buffer */
static uint8_t buffer[DISPLAY_WIDTH * DISPLAY_HEIGHT / 8];

#define SECOND (1000 / portTICK_PERIOD_MS)

static void wifi_init() {
    struct sdk_station_config wifi_config = {
        .ssid = WIFI_SSID,
        .password = WIFI_PASSWORD,
    };

    sdk_wifi_set_opmode(STATION_MODE);
    sdk_wifi_station_set_config(&wifi_config);
    sdk_wifi_station_connect();
}

void thermostat_identify(homekit_value_t _value) {
    printf("Thermostat identify\n");
}

ETSTimer fan_timer;

void heaterOn() {
    gpio_write(HEATER_PIN, false);
}

void heaterOff() {
    gpio_write(HEATER_PIN, true);
}

void coolerOn() {
    gpio_write(COOLER_PIN, false);
}

void coolerOff() {
    gpio_write(COOLER_PIN, true);
}

void fan_alarm(void *arg) {
    gpio_write(FAN_PIN, false);
}

void fanOn(uint16_t delay) {
    if (delay > 0) {
        sdk_os_timer_arm(&fan_timer, delay, false);
    } else {
        gpio_write(FAN_PIN, false);
    }
}

void fanOff() {
    sdk_os_timer_disarm(&fan_timer);
    gpio_write(FAN_PIN, true);
}

void update_state();

homekit_characteristic_t current_temperature = HOMEKIT_CHARACTERISTIC_(
    CURRENT_TEMPERATURE, 0
);
homekit_characteristic_t target_temperature  = HOMEKIT_CHARACTERISTIC_(
    TARGET_TEMPERATURE, 22, .callback=HOMEKIT_CHARACTERISTIC_CALLBACK(on_update)
);
homekit_characteristic_t units = HOMEKIT_CHARACTERISTIC_(TEMPERATURE_DISPLAY_UNITS, 0);
homekit_characteristic_t current_state = HOMEKIT_CHARACTERISTIC_(CURRENT_HEATING_COOLING_STATE, 0);
homekit_characteristic_t target_state = HOMEKIT_CHARACTERISTIC_(
    TARGET_HEATING_COOLING_STATE, 0, .callback=HOMEKIT_CHARACTERISTIC_CALLBACK(on_update)
);
homekit_characteristic_t cooling_threshold = HOMEKIT_CHARACTERISTIC_(
    COOLING_THRESHOLD_TEMPERATURE, 25, .callback=HOMEKIT_CHARACTERISTIC_CALLBACK(on_update)
);
homekit_characteristic_t heating_threshold = HOMEKIT_CHARACTERISTIC_(
    HEATING_THRESHOLD_TEMPERATURE, 15, .callback=HOMEKIT_CHARACTERISTIC_CALLBACK(on_update)
);
homekit_characteristic_t current_humidity = HOMEKIT_CHARACTERISTIC_(CURRENT_RELATIVE_HUMIDITY, 0);

void update_state() {
    uint8_t state = target_state.value.int_value;
    if ((state == 1 && current_temperature.value.float_value < target_temperature.value.float_value) ||
            (state == 3 && current_temperature.value.float_value < heating_threshold.value.float_value)) {
        if (current_state.value.int_value != 1) {
            current_state.value = HOMEKIT_UINT8(1);
            homekit_characteristic_notify(&current_state, current_state.value);

            heaterOn();
            coolerOff();
            fanOff();
            fanOn(HEATER_FAN_DELAY);
        }
    } else if ((state == 2 && current_temperature.value.float_value > target_temperature.value.float_value) ||
            (state == 3 && current_temperature.value.float_value > cooling_threshold.value.float_value)) {
        if (current_state.value.int_value != 2) {
            current_state.value = HOMEKIT_UINT8(2);
            homekit_characteristic_notify(&current_state, current_state.value);

            coolerOn();
            heaterOff();
            fanOff();
            fanOn(COOLER_FAN_DELAY);
        }
    } else {
        if (current_state.value.int_value != 0) {
            current_state.value = HOMEKIT_UINT8(0);
            homekit_characteristic_notify(&current_state, current_state.value);

            coolerOff();
            heaterOff();
            fanOff();
        }
    }
}

void temperature_sensor_task(void *_args) {
    sdk_os_timer_setfn(&fan_timer, fan_alarm, NULL);

    gpio_set_pullup(TEMPERATURE_SENSOR_PIN, false, false);

    gpio_enable(FAN_PIN, GPIO_OUTPUT);
    gpio_enable(HEATER_PIN, GPIO_OUTPUT);
    gpio_enable(COOLER_PIN, GPIO_OUTPUT);

    fanOff();
    heaterOff();
    coolerOff();

    float humidity_value, temperature_value;
    while (1) {
        bool success = dht_read_float_data(
            DHT_TYPE_DHT11, TEMPERATURE_SENSOR_PIN,
            &humidity_value, &temperature_value
        );
        if (success) {
            printf("Got readings: temperature %g, humidity %g\n", temperature_value, humidity_value);
            current_temperature.value = HOMEKIT_FLOAT(temperature_value);
            current_humidity.value = HOMEKIT_FLOAT(humidity_value);

            homekit_characteristic_notify(&current_temperature, current_temperature.value);
            homekit_characteristic_notify(&current_humidity, current_humidity.value);

            update_state();
        } else {
            printf("Couldnt read data from sensor\n");
        }

        vTaskDelay(TEMPERATURE_POLL_PERIOD / portTICK_PERIOD_MS);
    }
}

//***************OLED********************

static void ssd1306_task(void *pvParameters)
{
    printf("%s: Started user interface task\n", __FUNCTION__);
    vTaskDelay(SECOND);

    ssd1306_set_whole_display_lighting(&dev, false);

    while (1) {

       ssd1306_fill_rectangle(&dev, buffer, 0, 0, DISPLAY_WIDTH, DISPLAY_HEIGHT/2, OLED_COLOR_BLACK);
       ssd1306_draw_string(&dev, buffer, font_builtin_fonts[18], 30, 0, "27", OLED_COLOR_WHITE, OLED_COLOR_BLACK);
 
        if (ssd1306_load_frame_buffer(&dev, buffer))
            goto error_loop;

      //  frame_done++;
    }

error_loop:
    printf("%s: error while loading framebuffer into SSD1306\n", __func__);
    for (;;) {
        vTaskDelay(2 * SECOND);
        printf("%s: error loop\n", __FUNCTION__);
    }
}
 //*********************************

void thermostat_init() {
    xTaskCreate(temperature_sensor_task, "Thermostat", 256, NULL, 2, NULL);
    
   
}

void screen_init(){

   printf("SDK version:%s\n", sdk_system_get_sdk_version());

#ifdef I2C_CONNECTION
    i2c_init(I2C_BUS, SCL_PIN, SDA_PIN, I2C_FREQ_400K);
#endif

    while (ssd1306_init(&dev) != 0) {
        printf("%s: failed to init SSD1306 lcd\n", __func__);
        vTaskDelay(SECOND);
    }
    ssd1306_set_whole_display_lighting(&dev, true);
   vTaskDelay(SECOND);
   
    xTaskCreate(ssd1306_task, "ssd1306_task", 256, NULL, 2, NULL);

}

void on_update(homekit_characteristic_t *ch, homekit_value_t value, void *context) {
    update_state();
}

homekit_accessory_t *accessories[] = {
    HOMEKIT_ACCESSORY(.id=1, .category=homekit_accessory_category_thermostat, .services=(homekit_service_t*[]) {
        HOMEKIT_SERVICE(ACCESSORY_INFORMATION, .characteristics=(homekit_characteristic_t*[]) {
            HOMEKIT_CHARACTERISTIC(NAME, "Thermostat"),
            HOMEKIT_CHARACTERISTIC(MANUFACTURER, "HaPK"),
            HOMEKIT_CHARACTERISTIC(SERIAL_NUMBER, "001"),
            HOMEKIT_CHARACTERISTIC(MODEL, "MyThermostat"),
            HOMEKIT_CHARACTERISTIC(FIRMWARE_REVISION, "0.1"),
            HOMEKIT_CHARACTERISTIC(IDENTIFY, thermostat_identify),
            NULL
        }),
        HOMEKIT_SERVICE(THERMOSTAT, .primary=true, .characteristics=(homekit_characteristic_t*[]) {
            HOMEKIT_CHARACTERISTIC(NAME, "Thermostat"),
            &current_temperature,
            &target_temperature,
            &current_state,
            &target_state,
            &cooling_threshold,
            &heating_threshold,
            &units,
            &current_humidity,
            NULL
        }),
        NULL
    }),
    NULL
};

homekit_server_config_t config = {
    .accessories = accessories,
    .password = "111-11-111"
};

void user_init(void) {
    uart_set_baud(0, 115200);
	
	screen_init();
    
    wifi_init();
    thermostat_init();
    
    
    
    homekit_server_init(&config);
}

**Comment by maccoylton** [comment]
Checkout my thermostat example https://github.com/maccoylton/homekit_wifi_thermostat/blob/master/src/wifi_thermostat.c

**Comment by maccoylton** [comment]
try incrementing the stack size to 512k 

instead of 

xTaskCreate(ssd1306_task, "ssd1306_task", 256, NULL, 2, NULL);

try 

xTaskCreate(ssd1306_task, "ssd1306_task", **512**, NULL, 2, NULL);

**Comment by maximkulkin** [comment]
@xrust83 Can you show the complete source code

**Comment by maximkulkin** [comment]
@xrust83 The code seem fine. Can you describe the issue in more detail: you're saying that you press the "up" or "down" button, the screen lights up, but it shows the temperature that was set before? Does the temperature change in Home app?
Then, you're saying that if you press the "up" or "down" button again, then the screen is updated with a new temperature?

**Comment by maximkulkin** [comment]
@xrust83 Gotcha. In this case you need to modify [up_button_callback()](https://github.com/xrust83/homekit_wifi_thermostat/blob/master/src/wifi_thermostat.c#L485) and [down_button_callback()](https://github.com/xrust83/homekit_wifi_thermostat/blob/master/src/wifi_thermostat.c#L498) to check if screen is on. If not, just turn on screen and exit. Otherwise, modify temperature AND extend screen off delay:

```c
void up_button_callback(uint8_t gpio, void* args, const uint8_t param) {
    printf("Button UP single press\n");

    bool modify_temperature = screen_on;
    switch_screen_on(SCREEN_DELAY); /* ensure the screen is on and extend its off timer */
    
    if (!modify_temperature) return;

    if (target_temperature.value.float_value <= (target_temperature.max_value[0] - 0.5))
    {
        target_temperature.value.float_value += 0.5;
        sdk_os_timer_arm (&save_timer, SAVE_DELAY, 0 );
        homekit_characteristic_notify(&target_temperature, target_temperature.value);
    }
}
```
(same applies to down_button_callback()).
