### ISSUE TITLE
Ip camera RTPS

### ISSUE THREAD

**Issue by ur5zeb** [maximkulkin/esp-homekit-demo#150]
Hi 
IP camera via RTPS Is it possible?

**Comment by misha-marinenko-official** [comment]
Maybe rtsp?
No it isn't possible. Because esp is dont have needed hardware and libraries

**Comment by misha-marinenko-official** [comment]
Use HAP-Nodejs

**Comment by maximkulkin** [comment]
ESP8266 does not have enough resources so nobody even tries to come up with a camera sensor hardware attached to it. However, ESP32 should have enough resources and there are ESP32 modules with a camera sensor. You can google "m5stack camera psram". However, implementing an IP camera software is still an exercise. I have a [separate repository](https://github.com/maximkulkin/esp32-homekit-camera) for it, but live streaming is still not implemented.
