### ISSUE TITLE
BME280 code incorporation (and thanks)

### ISSUE THREAD

**Issue by HSkul** [maximkulkin/esp-homekit-demo#151]
This is not an issue, I was just wondering if anyone knew how difficult it would be to create an example of using BME280 based on the Adafruit BME280/ESP8266 library (before I really commit some time to it).  I'd like to swap out my Raspberry Pi running Homebridge with a BME280 for an ESP8266.

  BTW, thanks for this code and the directions.  I got my ESP8266 running pretty much right away with a 12 LED NeoPixel ring from Adafruit.  Everything worked right "out of the box".

  Hskul

**Comment by Kristian8606** [comment]
I also have interest to replace dht22 with bme280 I will write sample code when my sensor is delivered.

**Comment by Kristian8606** [comment]
BMP280/BME280  https://github.com/Kristian8606/Temperature_sensor
