### ISSUE TITLE
Motion Sensor example?

### ISSUE THREAD

**Issue by Einstein2150** [maximkulkin/esp-homekit-demo#158]
Can you make a motion sensor example? I have a motion sensor from Arduino which works with the Button-Example but triggers single, double or long press. Can you build one with the correct event and motion-type?

**Comment by peros550** [comment]
You may want to check the following repository : 

https://github.com/maccoylton/esp-homekit-motion-sensor

**Comment by Einstein2150** [comment]
Works like a charm. Thank you.
