### ISSUE TITLE
Shelly 1

### ISSUE THREAD

**Issue by tomasrocchetti** [maximkulkin/esp-homekit-demo#159]
Have anyone tried this firmware in shelly 1? I’m not able to use the external switch. I use it as a simple button on GPIO5, but it doesn’t work

**Comment by RavenSystem** [comment]
@tomasrocchetti you can see a working Shelly1 example here: 
https://github.com/RavenSystem/esp-homekit-devices/blob/master/devices/KellyTron/main.c

And here is a firmware that supports Shelly1 and Shelly2:
https://github.com/RavenSystem/esp-homekit-devices/wiki
