### ISSUE TITLE
433 MHz tx?

### ISSUE THREAD

**Issue by DominikTo** [maximkulkin/esp-homekit-demo#162]
Did anyone build a 433 MHz TX project on this? E.g. to remote control cheap 433 MHz outlets via HomeKit?

**Comment by maccoylton** [comment]
There is a 433MHz library that has been submitted as an extra for esp-open-rtos, it should be fairly easy to use this to build a bridge style device. It can be found here:- https://github.com/Felix5721/rf433mhz

**Comment by NorthernMan54** [comment]
I did this via homebridge 

https://github.com/NorthernMan54/homebridge-HTTP-IRBlaster

I found the challenge was around managing the transmitter codes, I have several devices and just use one esp8266/tx module to control them.  While in homebridge I have about a dozen devices configured

**Comment by lukasa1993** [comment]
why this was closed would be cool to have such option

**Comment by maximkulkin** [comment]
It might indeed be cool, but.. I do not plan to implement this and I'm not aware if anybody else plans to, so what's the point of having it hanging in list of open issues?

**Comment by lukasa1993** [comment]
is implementing this harder then other samples?

**Comment by maximkulkin** [comment]
I do not know and why does it matter?
