### ISSUE TITLE
I can't, simply I can't even start.

### ISSUE THREAD

**Issue by 4Xsample** [maximkulkin/esp-homekit-demo#164]
I'm absolutely a noob on this, and I can't even start with this project.
I'm trying to install this stuff but when I reach some point I simply can't continue, I got an error wich stops me.

I don't know if this forum is the right one for this kind of problems but I drop here what I did and what I get

sudo hdiutil create ~/Documents/case-sensitive.dmg -volname "case-sensitive" -size 10g -fs "Case-sensitive HFS+"

sudo hdiutil mount ~/Documents/case-sensitive.dmg

cd /Volumes/case-sensitive  brew tap homebrew/dupes brew tap homebrew/core

brew install binutils coreutils automake wget gawk libtool help2man gperf gnu-sed --with-default-names grep

git clone --recursive https://github.com/maximkulkin/esp-homekit-demo.git 
git clone --recursive https://github.com/pfalcon/esp-open-sdk.git 
git clone --recursive https://github.com/SuperHouse/esp-open-rtos.git

cd esp-open-sdk/ 

make toolchain esptool libhal STANDALONE=n

And here starts the show

  MacBook-Pro-de-Jordi-Rossell-Ferrer-9:esp-open-sdk rossell_j$ make toolchain esptool libhal STANDALONE=n
Makefile:186: warning: overriding commands for target `ESP8266_NONOS_SDK-2.1.0-18-g61248df/.dir'
Makefile:181: warning: ignoring old commands for target `ESP8266_NONOS_SDK-2.1.0-18-g61248df/.dir'
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C crosstool-NG -f ../Makefile _ct-ng
../Makefile:186: warning: overriding commands for target `ESP8266_NONOS_SDK-2.1.0-18-g61248df/.dir'
../Makefile:181: warning: ignoring old commands for target `ESP8266_NONOS_SDK-2.1.0-18-g61248df/.dir'
./bootstrap
Running autoconf...
Done. You may now run:
    ./configure
./configure --prefix=`pwd`
checking build system type... x86_64-apple-darwin18.2.0
checking host system type... x86_64-apple-darwin18.2.0
checking for a BSD-compatible install... /usr/local/opt/coreutils/libexec/gnubin/install -c
checking for grep that handles long lines and -e... /usr/local/opt/grep/libexec/gnubin/grep
checking for egrep... /usr/local/opt/grep/libexec/gnubin/grep -E
checking for a sed that does not truncate output... /usr/local/opt/gnu-sed/libexec/gnubin/sed
checking whether sed understands -r -i -e... yes
checking whether ln -s works... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for ranlib... ranlib
checking for gobjcopy... gobjcopy
checking for absolute path to gobjcopy... /usr/local/opt/binutils/bin/gobjcopy
checking for gobjdump... gobjdump
checking for absolute path to gobjdump... /usr/local/opt/binutils/bin/gobjdump
checking for greadelf... greadelf
checking for absolute path to greadelf... /usr/local/opt/binutils/bin/greadelf
checking for gperf... gperf
checking for absolute path to gperf... /usr/local/bin/gperf
checking for bison... bison
checking for flex... flex
checking for makeinfo... makeinfo
checking for cut... cut
checking for stat... stat
checking for readlink... readlink
checking for wget... wget
checking for tar... tar
checking for gzip... gzip
checking for bzip2... bzip2
checking for help2man... help2man
checking for gpatch... no
checking for patch... patch
checking for absolute path to patch... /usr/bin/patch
checking for bash >= 3.1... /bin/bash
checking for GNU awk... /usr/local/bin/gawk
checking for GNU make >= 3.80... /usr/bin/make
checking whether /usr/bin/make sets $(MAKE)... yes
checking for make 3.81... yes
checking for GNU libtool >= 1.5.26... /usr/local/bin/glibtool
checking for GNU libtoolize >= 1.5.26... /usr/local/bin/glibtoolize
checking for GNU automake >= 1.10... /usr/local/bin/automake
checking for the type used in gperf declarations... size_t
checking for xz... no
checking for lzma... no
checking for cvs... no
checking for svn... svn
checking for inline... inline
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for size_t... yes
checking for working alloca.h... yes
checking for alloca... yes
checking libintl.h usability... no
checking libintl.h presence... no
checking for libintl.h... no
checking for library containing bindtextdomain... no
checking ncurses/ncurses.h usability... no
checking ncurses/ncurses.h presence... no
checking for ncurses/ncurses.h... no
checking ncurses/curses.h usability... no
checking ncurses/curses.h presence... no
checking for ncurses/curses.h... no
checking ncursesw/curses.h usability... no
checking ncursesw/curses.h presence... no
checking for ncursesw/curses.h... no
checking ncurses.h usability... yes
checking ncurses.h presence... yes
checking for ncurses.h... yes
checking for library containing initscr... -lncurses
checking for library containing tgetent... none required
configure: creating ./config.status
config.status: creating Makefile
/Applications/Xcode.app/Contents/Developer/usr/bin/make MAKELEVEL=0
  SED    'ct-ng'
  SED    'scripts/crosstool-NG.sh'
  SED    'scripts/saveSample.sh'
  SED    'scripts/showTuple.sh'
  GEN    'config/configure.in'
  GEN    'paths.mk'
  GEN    'paths.sh'
  DEP    'nconf.gui.dep'
  DEP    'nconf.dep'
  DEP    'lxdialog/yesno.dep'
  DEP    'lxdialog/util.dep'
  DEP    'lxdialog/textbox.dep'
  DEP    'lxdialog/menubox.dep'
  DEP    'lxdialog/inputbox.dep'
  DEP    'lxdialog/checklist.dep'
  DEP    'mconf.dep'
  DEP    'conf.dep'
  BISON  'zconf.tab.c'
  GPERF  'zconf.hash.c'
  LEX    'zconf.lex.c'
  DEP    'zconf.tab.dep'
  CC     'zconf.tab.o'
  CC     'conf.o'
  LD     'conf'
  CC     'lxdialog/checklist.o'
  CC     'lxdialog/inputbox.o'
  CC     'lxdialog/menubox.o'
  CC     'lxdialog/textbox.o'
  CC     'lxdialog/util.o'
  CC     'lxdialog/yesno.o'
  CC     'mconf.o'
  LD     'mconf'
  CC     'nconf.o'
  CC     'nconf.gui.o'
  LD     'nconf'
Undefined symbols for architecture x86_64:
  "_current_item", referenced from:
      _item_data in nconf.o
      _curses_item_index in nconf.o
      _item_tag in nconf.o
      _get_mext_match in nconf.o
      _btn_dialog in nconf.gui.o
  "_free_item", referenced from:
      _clean_items in nconf.o
      _item_add_str in nconf.o
      _btn_dialog in nconf.gui.o
  "_free_menu", referenced from:
      _main in nconf.o
      _btn_dialog in nconf.gui.o
  "_item_count", referenced from:
      _center_item in nconf.o
  "_item_index", referenced from:
      _curses_item_index in nconf.o
      _get_mext_match in nconf.o
      _btn_dialog in nconf.gui.o
  "_item_userptr", referenced from:
      _item_data in nconf.o
      _item_tag in nconf.o
  "_menu_driver", referenced from:
      _conf in nconf.o
      _conf_choice in nconf.o
      _btn_dialog in nconf.gui.o
  "_menu_opts_off", referenced from:
      _main in nconf.o
      _btn_dialog in nconf.gui.o
  "_menu_opts_on", referenced from:
      _main in nconf.o
      _btn_dialog in nconf.gui.o
  "_menu_win", referenced from:
      _conf in nconf.o
      _conf_choice in nconf.o
  "_new_item", referenced from:
      _item_make in nconf.o
      _item_add_str in nconf.o
      _btn_dialog in nconf.gui.o
  "_new_menu", referenced from:
      _main in nconf.o
      _btn_dialog in nconf.gui.o
  "_post_menu", referenced from:
      _show_menu in nconf.o
      _center_item in nconf.o
      _btn_dialog in nconf.gui.o
  "_scale_menu", referenced from:
      _show_menu in nconf.o
  "_set_current_item", referenced from:
      _center_item in nconf.o
  "_set_item_userptr", referenced from:
      _item_make in nconf.o
      _item_add_str in nconf.o
  "_set_menu_back", referenced from:
      _main in nconf.o
      _btn_dialog in nconf.gui.o
  "_set_menu_fore", referenced from:
      _main in nconf.o
      _btn_dialog in nconf.gui.o
  "_set_menu_format", referenced from:
      _show_menu in nconf.o
      _btn_dialog in nconf.gui.o
  "_set_menu_grey", referenced from:
      _main in nconf.o
  "_set_menu_items", referenced from:
      _show_menu in nconf.o
  "_set_menu_mark", referenced from:
      _main in nconf.o
      _btn_dialog in nconf.gui.o
  "_set_menu_sub", referenced from:
      _show_menu in nconf.o
      _btn_dialog in nconf.gui.o
  "_set_menu_win", referenced from:
      _show_menu in nconf.o
      _btn_dialog in nconf.gui.o
  "_set_top_row", referenced from:
      _center_item in nconf.o
  "_top_row", referenced from:
      _conf in nconf.o
      _center_item in nconf.o
      _conf_choice in nconf.o
  "_unpost_menu", referenced from:
      _main in nconf.o
      _reset_menu in nconf.o
      _btn_dialog in nconf.gui.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [nconf] Error 1
make: *** [build-lib-kconfig] Error 2
make: *** [build] Error 2
make[1]: *** [_ct-ng] Error 2
make: *** [crosstool-NG/ct-ng] Error 2

**Comment by maximkulkin** [comment]
I agree, using it on Mac is kind of painful since brew does not put stuff where it should be. I personally solved that problem by installing everything in a docker container. It requires additional steps to use, but you have no problems with stuff not being found or being of wrong version.

https://gist.github.com/maximkulkin/bca710444cbbc01a1845687a266f45a4

**Comment by smilespray** [comment]
I created a Ubuntu virtual machine in VirtualBox after struggling for days with a Mac install.
Worked a lot smoother.

**Comment by 4Xsample** [comment]
> I agree, using it on Mac is kind of painful since brew does not put stuff where it should be. I personally solved that problem by installing everything in a docker container. It requires additional steps to use, but you have no problems with stuff not being found or being of wrong version.
> 
> https://gist.github.com/maximkulkin/bca710444cbbc01a1845687a266f45a4

I'll try this way!!
Thanks for your help!!!

**Comment by 4Xsample** [comment]
> I created a Ubuntu virtual machine in VirtualBox after struggling for days with a Mac install.
> Worked a lot smoother.

I was thinking this as an alternative, or even work it from some of my raspberryes.
But my mac is kinda old (early 2013) and will struggle a bit with a virtual machine and the option of a raspberry ties me to my desk.
If I can't make it work on the hard way I'll choose this trick.
Thanks for your help.

**Comment by sakisdog** [comment]
@4Xsample You can use Vagrant and VirtualBox to almost automate the whole process. I created a video tutorial that shows the whole process.
@maximkulkin Is it ok if i post the link here?

**Comment by maximkulkin** [comment]
@sakisdog I do not mind

**Comment by sakisdog** [comment]
https://youtu.be/QBj8OLig8Kg
@maximkulkin Thanks for the effort and time you put on this project!
