### ISSUE TITLE
Devices don't work remotely through Home Hub (Apple TV)

### ISSUE THREAD

**Issue by wasp100** [maximkulkin/esp-homekit-demo#170]
Hi,
I noticed that when trying to control the devices remotely (I have an Apple TV which acts as the Home Hub), the devices show up as "No Response". 

However, when I'm on my local wifi network, the devices work perfectly!

Has anyone else picked this up, and is there a fix for this? I've tried it with the LED code as well as the Sonoff code.

Thanks!

**Comment by wasp100** [comment]
@maximkulkin

**Comment by maximkulkin** [comment]
Is Apple TV at the same WiFi network as devices?

I have Apple TV and it works great: e.g. I have an automation that turns on living room lights at 8pm.

**Comment by wasp100** [comment]
Yes, it’s on the same network. 
All my other HomeKit devices work perfectly with the Apple TV. 
I’ve restarted the Apple TV as well, but no luck. 
Anything else I should try?

**Comment by wasp100** [comment]
What I noticed is when I’ve disconnected the power from the device and reconnected (to simulate a power outage), the device would show as No Response over cellular, yet connect when on local Wifi. 
Can you perhaps try this with your lights? Disconnect the HomeKit device and reconnect and see whether you can control remotely over cellular?

**Comment by maximkulkin** [comment]
It does this because iOS controllers are slow to reconnect after connection termination (since Apple TV keeps connections to all accessories) while on iPhone if you just opened the Home app, it reconnects to them. I believe the same would happen with all certified accessories.

**Comment by wasp100** [comment]
I tested your hypothesis by switching off my other HomeKit Wi-Fi accessories along with the maximkulkin device. 
The HomeKit Wi-Fi devices returned their states after 2-3 minutes. 
The maximkulkin device is still showing No Respinse over cellular. If I change over to Wi-Fi, it shows the correct state. As soon as I toggle over to cellular, it shows No Response again. :(

**Comment by wasp100** [comment]
@maximkulkin 
Have you managed to recreate this with your setup?

**Comment by peros550** [comment]
Guys, try to power reset  Apple TV and all Wifi devices (Router, AP, extenders)  when troubleshooting.
