### ISSUE TITLE
Build for ESP32: Fatal error: etstimer.h: No such file

### ISSUE THREAD

**Issue by Christian1313** [maximkulkin/esp-homekit-demo#172]
I followed the instructions up to the point 5. Build example.

I deleted the component  WS2812FX due to previous build error (see #84 ).

But then I got:

```
... esp-homekit-demo/components/led-status/led_status.c:3:22: fatal error: etstimer.h: No such file or directory
compilation terminated.

make[1]: *** [led_status.o] Error 1

make: *** [component-led-status-build] Error 2
```

Additional infos:

I am building on Mac. Added the sdkconfig below.

[sdkconfig.txt](https://github.com/maximkulkin/esp-homekit-demo/files/2889433/sdkconfig.txt)

**Comment by maximkulkin** [comment]
led-status is an example for esp8266. ESP32 examples are under examples/esp32 and right now there is only one example there.

**Comment by shaurya0406** [comment]
I am also getting the same build error while compiling esp32/led example.

**Comment by maximkulkin** [comment]
ok, this caused by the fact that some of components were esp8266-/esp32-only and build system was dumb enough to help separating them.. So I just pushed a change that splits components into 3 categories.. This should fix problem of component clashes.

Should compile now.

**Comment by shaurya0406** [comment]
It compiled successfully.
Thanks
