### ISSUE TITLE
Sonoff Touch support?

### ISSUE THREAD

**Issue by danio0701** [maximkulkin/esp-homekit-demo#175]
Hi,

I have a trouble to find example files to Sonoff Touch light wall switch :(

Any ideas or links where I can find files examples?

thanks a lot for suggestions.

**Comment by maximkulkin** [comment]
There is none, but you can contribute one

**Comment by danio0701** [comment]
> There is none, but you can contribute one

Ok, Is it possible to download from sonoff touch full configuration with soft or basic? I'm asking because a local store is selling sonoff touch with homekit software and if it possible I can try backup this firmware and upload here :)

**Comment by danio0701** [comment]
I founded article how to backup firmware so I will buy from them this sonoff devies, backup firmware and try to write on my sonoff :)

**Comment by nhatquang88** [comment]
> I founded article how to backup firmware so I will buy from them this sonoff devies, backup firmware and try to write on my sonoff :)

would u please share the firmware and how to flash it thank you
