### ISSUE TITLE
Can anyone help with the example of the door lock?

### ISSUE THREAD

**Issue by outsiderz** [maximkulkin/esp-homekit-demo#177]
Can anyone help with the example of the door lock?

**Comment by outsiderz** [comment]
![1600x_image](https://user-images.githubusercontent.com/26770800/54315623-a2a91100-45ef-11e9-9eb8-65ff77a3ca3d.png)

**Comment by maximkulkin** [comment]
I've just added a [lock example](https://github.com/maximkulkin/esp-homekit-demo/tree/master/examples/lock), check it out.

**Comment by outsiderz** [comment]
Спасибо огромное!!!
