### ISSUE TITLE
Setting Button Interrupt Routine for GPIOs

### ISSUE THREAD

**Issue by hwater** [maximkulkin/esp-homekit-demo#182]
Hello Maxim

Just reading your latest "doorlock" Example.
Why do you use the "GPIO_INTTYPE_EDGE_ANY" to set the Interrupt? 
So you allways get 2 Interupts for ANY Press, even the shortest. Maybe better to react only on RISING or FALLING. Or is it to be compatible with every HW-Design (pull up or down)?

I came upon this Effect by measuring the Frequency with an Hall-Sensor + Magnet on an Motor, to get the right Frequeny of Radiations i had to divide the Result by 2.

Nevertheless - i like your Implementation with these little Controllers and HomeKit very much!

Holger

**Comment by maximkulkin** [comment]
So, regarding raising or falling edge: you need them both to track long presses.
