### ISSUE TITLE
info magichome led strip

### ISSUE THREAD

**Issue by curla92** [maximkulkin/esp-homekit-demo#194]
Hi maxim. I would to know which led strip you used to test your magichome firmware. I tried with a simple rgb led strip but it doesn't work well. Colors are wrong and i was not able to resolve the problem. Thanks and i really appreciate your work.

**Comment by maximkulkin** [comment]
Colors might be wrong because different RGB LEDs have different color orders (e.g. RGB, GRB, GBR).. You just need to figure which one is yours and adjust. You can create a simple firmware that first sets all RED, then GREEN, then BLUE and notice the actual colors.

**Comment by curla92** [comment]
What's the GPIO scheme?

**Comment by maximkulkin** [comment]
https://github.com/maximkulkin/esp-homekit-demo/blob/master/examples/led_strip/led_strip.c#L2-L9

**Comment by curla92** [comment]
i meant gpio scheme of magic home thank y

**Comment by maximkulkin** [comment]
What do you call gpio scheme?!

**Comment by curla92** [comment]
with espurna firmware my led strip works with this configuration.
    #define LIGHT_CH1_PIN       12      // RED
    #define LIGHT_CH2_PIN       5       // GREEN
    #define LIGHT_CH3_PIN       13      // BLUE
    #define LIGHT_CH4_PIN       14      // WHITE
