### ISSUE TITLE
analogRead

### ISSUE THREAD

**Issue by Mattis-Schulte** [maximkulkin/esp-homekit-demo#197]
Hello, I would like to use analogRead to read out my Temperature Sensor (LM35) and integrate it into Homekit. Unfortunately, I could not find a way to use analogRead, so I'll ask here

**Comment by maximkulkin** [comment]
[sdk_system_adc_read()](https://github.com/SuperHouse/esp-open-rtos/blob/a8c60e096093e9e9f4a60b885676adc2cf5b790a/include/espressif/esp_system.h#L80)
