### ISSUE TITLE
temperature sensor demo question

### ISSUE THREAD

**Issue by faronov** [maximkulkin/esp-homekit-demo#2]
I think it may be better to use ESP-OPEN-RTOS. for base
it has more sensor support 
but what type of temp sensor this demo is supported?

**Comment by renssies** [comment]
Currently the demo just sends a random number between 0 and 100 I believe. It doesnt actually use a sensor.

The LED demo uses the built in LED of most ESPs

**Comment by maximkulkin** [comment]
Exactly. I did not want to mess with any external libraries or in any other way complicate examples. Temperature sensor example was supposed to show how to handle values that are updated on their own, how to declare and use characteristics.

Although I might add real DHT11 implementation sometime later.

**Comment by maximkulkin** [comment]
Here you go guys! I've updated temperature_sensor example with real DHT11 integration code plus it now also exposes humidity information (because why not). Enjoy!

**Comment by medmile** [comment]
I have error “can not read data from sensor” error in bloc “B” (DHT11). On ESP8266_RTOS_SDK sensor work good. Am I need to use resistor?

**Comment by maximkulkin** [comment]
That is probably because you've specified incorrect GPIO pin number. Pin numberss might be different from Espressif SDK (myself had to do a couple of trial and error attempts before settling down correct one).

**Comment by medmile** [comment]
I test nodemcu v3. Pin №4 (D2). Led example work on this pin.

**Comment by maximkulkin** [comment]
Here is how I tested: I opened NodeMCU pinout 
![nodemcu_pins](https://user-images.githubusercontent.com/10785/33878011-1358dc42-dedf-11e7-8afe-a700819470f8.png), set SENSOR_PIN=4 in Makefile and connect DHT11 data output to NodeMCU's D2 (GPIO4). Although this method did not work for me for combination GPIO16 and D0.

**Comment by maximkulkin** [comment]
That is strange because this is exactly the set up that worked for me. Could you provide your wiring schematics.

**Comment by medmile** [comment]
![file](https://user-images.githubusercontent.com/2050606/33878632-1046df28-df3d-11e7-9d54-c05881b66003.jpeg)
![file1](https://user-images.githubusercontent.com/2050606/33878634-106794d4-df3d-11e7-9857-cd988b8d44a2.jpeg)

**Comment by maximkulkin** [comment]
Not sure what kind of break out you've got, but on mine (which looks exactly like this) data pin is in center while on your layout it's on the left. Are you sure you've connected everything properly?

**Comment by maximkulkin** [comment]
Ok, the image of DHT is very blury, but it looks like your pin layout is correct. What I've noticed is: my breakout has embedded pull-up resistor (along with capacitor), so maybe you need to change [line 60](https://github.com/maximkulkin/esp-homekit-demo/blob/master/examples/temperature_sensor/temperature_sensor.c#L60) to enable pull-up on ESP8266 side:
`gpio_set_pullup(SENSOR_PIN, true, false);`

**Comment by medmile** [comment]
I use this module. This work with ESP8266_RTOS_SDK...
![dht11-pinout-for-three-pin-and-four-pin-types-2-1024x742](https://user-images.githubusercontent.com/2050606/33879264-f8dfd50e-df3e-11e7-9b8e-a9c26ca0155d.jpg)

**Comment by maximkulkin** [comment]
Well, I'm out of ideas. I suggest you ask help in [esp-open-rtos](https://github.com/SuperHouse/esp-open-rtos) project. Try starting with their simple [dht_sensor](https://github.com/SuperHouse/esp-open-rtos/tree/master/examples/dht_sensor) example and make it work.

**Comment by medmile** [comment]
I noticed that there is a 10kom resistor on my module. Could this be the reason? Do you use a resistor?

**Comment by medmile** [comment]
I found mistake!
In dht.c first argument "dht_sensor_type_t":
bool dht_read_float_data(dht_sensor_type_t sensor_type, uint8_t pin, float *humidity, float *temperature)
{
    int16_t i_humidity, i_temp;

    if (dht_read_data(sensor_type, pin, &i_humidity, &i_temp)) {
        *humidity = (float)i_humidity / 10;
        *temperature = (float)i_temp / 10;
        return true;
    }
    return false;
}
but you use first argument "SENSOR_PIN":
bool success = dht_read_float_data(
            SENSOR_PIN, DHT_TYPE_DHT11,
            &humidity_value, &temperature_value
        );

**Comment by maximkulkin** [comment]
Oh! Thank you for reporting that. Fixed.

**Comment by faronov** [comment]
I see another strange behavior
It shows temperature and humidity, but continuously I get error
`HomeKit: [Client 5] Error reading data (code 128)`
It looks like it ask too many times for getting data
after some time it crashed

**Comment by maccoylton** [comment]
faronov, your not alone, I'm getting that error as well

**Comment by maximkulkin** [comment]
Pushed change to force disconnect client in case reading from socket results in an error.

**Comment by faronov** [comment]
As I see it fail after it shows IP
I increase vtask time , but it didn't help
```
>>> mdns_recv: pbuf too big
>>> HomeKit: Got new client connection: 4
>>> HomeKit: [Client 4] Pair Setup Step 1/3
>>> HomeKit: [Client 4] Pair Setup Step 2/3
>>> HomeKit: [Client 4] Pair Setup Step 3/3
>>> HomeKit: Added pairing with 1F4D9525-9246-430F-B309-538363BA9646
>>> HomeKit: Configuring mDNS
>>> HomeKit: [Client 4] Successfully paired
>>> HomeKit: [Client 4] Closing client connection
>>> HomeKit: Got new client connection: 4
>>> HomeKit: [Client 4] Pair Verify Step 1/2
>>> HomeKit: [Client 4] Pair Verify Step 2/2
>>> HomeKit: [Client 4] Found pairing with 1F4D9525-9246-430F-B309-538363BA9646
>>> HomeKit: [Client 4] Verification successful, secure session established
>>> HomeKit: [Client 4] Get Accessories
>>> HomeKit: [Client 4] Update Characteristics
>>> HomeKit: [Client 4] Update Characteristics
>>> HomeKit: Got new client connection: 5
>>> HomeKit: [Client 5] Pair Verify Step 1/2
>>> HomeKit: [Client 5] Pair Verify Step 2/2
>>> HomeKit: [Client 5] Found pairing with 1F4D9525-9246-430F-B309-538363BA9646
>>> HomeKit: [Client 5] Verification successful, secure session established
>>> HomeKit: [Client 5] Get Accessories
>>> HomeKit: [Client 4] Get Characteristics
>>> HomeKit: [Client 4] Update Characteristics
Temperature sensor identify
>>> HomeKit: [Client 4] Get Characteristics
>>> HomeKit: [Client 4] Update Characteristics
Temperature sensor identify
>>> HomeKit: [Client 4] Get Characteristics
>>> HomeKit: [Client 5] Update Characteristics
>>> HomeKit: Got new client connection: 6
>>> HomeKit: [Client 6] Pair Verify Step 1/2
>>> HomeKit: [Client 6] Pair Verify Step 2/2
>>> HomeKit: [Client 6] Found pairing with 1F4D9525-9246-430F-B309-538363BA9646
>>> HomeKit: [Client 6] Verification successful, secure session established
>>> HomeKit: [Client 6] Get Accessories
ip:192.168.11.23,mask:255.255.255.0,gw:192.168.11.1
!!! HomeKit: [Client 5] Error reading data (code 104)
!!! HomeKit: [Client 5] Error reading data (code 104)
```

**Comment by faronov** [comment]
Next run
same result
dhcp client start...
```
ip:192.168.11.23,mask:255.255.255.0,gw:192.168.11.1
>>> HomeKit: Got IP, starting
>>> HomeKit: Configuring mDNS
>>> HomeKit: Got new client connection: 4
>>> HomeKit: [Client 4] Pair Setup Step 1/3
>>> HomeKit: [Client 4] Pair Setup Step 2/3
>>> HomeKit: [Client 4] Pair Setup Step 3/3
>>> HomeKit: Added pairing with 1F4D9525-9246-430F-B309-538363BA9646
>>> HomeKit: Configuring mDNS
>>> HomeKit: [Client 4] Successfully paired
>>> HomeKit: [Client 4] Closing client connection
>>> HomeKit: Got new client connection: 4
>>> HomeKit: [Client 4] Pair Verify Step 1/2
>>> HomeKit: [Client 4] Pair Verify Step 2/2
>>> HomeKit: [Client 4] Found pairing with 1F4D9525-9246-430F-B309-538363BA9646
>>> HomeKit: [Client 4] Verification successful, secure session established
>>> HomeKit: [Client 4] Get Accessories
>>> HomeKit: [Client 4] Update Characteristics
>>> HomeKit: [Client 4] Update Characteristics
>>> HomeKit: Got new client connection: 5
>>> HomeKit: [Client 5] Pair Verify Step 1/2
>>> HomeKit: [Client 5] Pair Verify Step 2/2
>>> HomeKit: [Client 5] Found pairing with 1F4D9525-9246-430F-B309-538363BA9646
>>> HomeKit: [Client 5] Verification successful, secure session established
>>> HomeKit: [Client 5] Get Accessories
>>> HomeKit: [Client 4] Get Characteristics
>>> HomeKit: [Client 4] Update Characteristics
Temperature sensor identify
>>> HomeKit: [Client 4] Get Characteristics
>>> HomeKit: [Client 4] Update Characteristics
Temperature sensor identify
>>> HomeKit: [Client 4] Get Characteristics
>>> HomeKit: [Client 5] Update Characteristics
>>> HomeKit: Got new client connection: 6
>>> HomeKit: [Client 6] Pair Verify Step 1/2
>>> HomeKit: [Client 6] Pair Verify Step 2/2
>>> HomeKit: [Client 6] Found pairing with 1F4D9525-9246-430F-B309-538363BA9646
>>> HomeKit: [Client 6] Verification successful, secure session established
>>> HomeKit: [Client 6] Get Accessories
>>> HomeKit: [Client 5] Get Characteristics
>>> HomeKit: [Client 5] Update Characteristics
>>> HomeKit: [Client 5] Update Characteristics
ip:192.168.11.23,mask:255.255.255.0,gw:192.168.11.1
Couldnt read data from sensor

```

**Comment by maximkulkin** [comment]
`Couldnt read data from sensor` seem to be irrelevant to HomeKit.

Regarding `!!! HomeKit: [Client 5] Error reading data (code 104)`: this should be fixed in latest code, server will drop clients with (unknown) socket errors. I found another problem: sometimes it does not detect clients being gone and eventually accumulates maximum number of clients (8), refusing to accept new ones. I'm doing long term testing of a fix for this one and will push soon.

BTW, how do you trigger "Identify" multiple times without repairing? I couldn't find a button in Home.app to do that.

**Comment by faronov** [comment]
I think one identity from thermometer
and second from humidity

**Comment by HomeACcessoryKid** [comment]
Identify is accessible if you use the Eve App from ElGato

**Comment by orisraeli** [comment]
could this work with DHT22 sensor?

**Comment by maximkulkin** [comment]
Yes, the library that is used there supports both DHT11 and DHT22, you just need to pass it which version of sensor you have.

**Comment by LiangyongFShen** [comment]
@faronov Have you solved your problem? I have the same problem, except the separate pairing switch, other devices cannot be paired。
