### ISSUE TITLE
 I lose the wi-fi data on restart

### ISSUE THREAD

**Issue by oremic** [maximkulkin/esp-homekit-demo#202]
I entered
http-client-ota @andreagreco in the example sonoff basic.
flash size 8m set.
On reboot after ota update.
"wifi_config: No configuration found"
loses some data.
how can i solve.
thanks

**Comment by maximkulkin** [comment]
I would suggest: do not use OTA update unless you know what you're doing or ask this question on their project.

**Comment by oremic** [comment]
ok i will ask them.
thank you
