### ISSUE TITLE
button

### ISSUE THREAD

**Issue by AchimPieters** [maximkulkin/esp-homekit-demo#205]
Hi Maxim,

I have I little problem with your button demo.

My hardware is build like this:
![HomeKit Light Switch_bb](https://user-images.githubusercontent.com/16034588/56823735-f9dc0b80-6854-11e9-814a-84c124e3a159.png)

unfortunately I can't get it to work properly, because when I push the button I says long press or sometimes double press.

I tried changing the button.c part:

```
// times in milliseconds
    button->debounce_time = 50;
    button->long_press_time = 1000;
    button->double_press_time = 500;
```

to other milliseconds, but not with the right results. can you help me?

**Comment by maximkulkin** [comment]
I will look into it. When I wrote it more than a year ago it worked perfectly for me, but I've been getting reports about long press trigger before. Some people even stripped long press functionality from some button library copies (e.g. in sonoff_basic example). I'm certainly interested in keeping full functionality, so I will look into fixing it and extracting as a separate library (to finally stop it being copy-pasted everywhere).

**Comment by maximkulkin** [comment]
Ok, I have figured that out. You're using button in "active low" configuration (meaning signal goes low when button is pressed). Original button example was written for "active high" and thus everything is inverted in your case and you get long presses all the time.

You can fix it by changing [this line](https://github.com/maximkulkin/esp-homekit-demo/blob/master/examples/button/button.c#L48) to
```c
if (gpio_read(button->gpio_num) == 0) {
```

I have extracted button code into a separate library which allows configuring which active mode your button uses: [esp-button](https://github.com/maximkulkin/esp-button).

PS you do not need pullup resistors on buttons (shown on your wiring diagram), it will use built-in pullup resistors.

**Comment by AchimPieters** [comment]
Awesome :bangbang: you are the 👍 

I have a look into it tomorrow!
