### ISSUE TITLE
add example of linked service

### ISSUE THREAD

**Issue by 01matrix01** [maximkulkin/esp-homekit-demo#207]
Hi Maxim,
I'm trying to make a TV Service with the new Homekit services and characteristics of 12.2 IOS,
I'm trying to convert this homebridge plugin:
https://github.com/merdok/homebridge-webos-tv

In the code I see some "this.tvService.addLinkedService" and you have done linked support on your HOMEKIT library but how it works?

Can you post an example please?

Thanks in advance

**Comment by maximkulkin** [comment]
Here is [my implementation of a TV](https://github.com/maximkulkin/esp-ir-tv), you might find answers there.
