### ISSUE TITLE
Door Sensor pin contact information

### ISSUE THREAD

**Issue by nhatquang88** [maximkulkin/esp-homekit-demo#210]
Hi Sir,
Would you please tell me what kind of door sensor I should buy in order to work with your Firmware.
I flashed your firmware to the ESP8266 NodeMcu, but I don't know how to connect it.
Thank you and best regards

**Comment by maximkulkin** [comment]
Just a reminder that some examples where contributed by other users, not written by me.

I guess for door sensor you need a [reed switch](https://www.amazon.com/SpzcdZa-Magnetic-Normally-Security-Contact/dp/B07NHL174G/ref=mp_s_a_1_17?crid=3JFBGCAPPT9VP). Connect normally open contact to gpio pin and common one - to ground.
