### ISSUE TITLE
ESP8266 air quality sensor request

### ISSUE THREAD

**Issue by nhatquang88** [maximkulkin/esp-homekit-demo#213]
Hi Sir,
I wonder if you have time would u please make an Air Quality Sensor firmware for us.
I think it is very helpful at home.

**Comment by maccoylton** [comment]
I wrote one, you can find it here:- https://github.com/maccoylton/esp-homekit-air-quality-sensor

**Comment by nhatquang88** [comment]
@maccoylton I'm using your version now but it missing the sensor value.. I wish we can make a full version which read all of the value.. Thank you sir

**Comment by maccoylton** [comment]
I'm investigation options to add other sensors, will post updates as I make progress
