### ISSUE TITLE
Garage Door sensor Pin information

### ISSUE THREAD

**Issue by nhatquang88** [maximkulkin/esp-homekit-demo#217]
![A26D3D61-2299-44F8-8807-75FE919A0F3F](https://user-images.githubusercontent.com/49787353/57977499-cd667a00-7a23-11e9-8c3e-e355da175d6b.jpeg)
Hi sir
I would able to flash your Garage Door sensor to my NodeMCU esp8266
I wonder would u please provide more detail about Reed switch contact information to what GPIO in and Relay information 
Thank you

and I wonder what kind of relay I need to buy in order to make my system work?
Thank you a lot

here is my garage door button if I'm connect the ESP to it will it work?

**Comment by maximkulkin** [comment]
Ok, looks like you do not know what you're doing and thus I do not want to give any advise and be blamed for because you implementing it incorrectly, so I will just say - I don't know.
