### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by Mr18565433296** [maximkulkin/esp-homekit-demo#225]
Opt/esp8266/esp-homekit-demo/examples/esp8266-rgb-led-strip$ make -C . all
Make: Go to the directory "/opt/esp8266/esp-homekit-demo/examples/esp8266-rgb-led-strip"
Makefile:14: /common.mk: No such file or directory
Make: *** There is no rule to create the target "/common.mk". stop.
Make: leave the directory "/opt/esp8266/esp-homekit-demo/examples/esp8266-rgb-led-strip"

**Comment by maximkulkin** [comment]
You need to set SDK_PATH environment variable pointing to ESP-OPEN-RTOS
