### ISSUE TITLE
Wiki for Build instructions ESP8266 (Docker) Missing Some Steps

### ISSUE THREAD

**Issue by maczaur** [maximkulkin/esp-homekit-demo#239]
First off, great repo and documentation.

So I was following the guide and a couple of things are missing that it would be good to have added to the Wiki for ESP8266 Docker builds.

1. Python 2.7 needs to be installed before running the pip command to install the esptools

2. Wifi.h needs to be created using the sample in the esp-homekit-demo folder before building the sample.  Perhaps this could be mentioned in the Configuration Wiki page?

Sorry for not providing a pull request to do this but I'm new to GitHub and am not sure how to do it...

**Comment by maximkulkin** [comment]
Updated wiki
