### ISSUE TITLE
How to reset wifi

### ISSUE THREAD

**Issue by Hackxiaoya** [maximkulkin/esp-homekit-demo#248]
When I swiped in the firmware, my Wi-Fi changed after using it for a while. How do I reset the device?

**Comment by maximkulkin** [comment]
Support for reset is something each individual firmware has to implement. A lot of examples here targeting Sonoff devices implement reset by long pressing the button (since Sonoffs have a button). Check your firmware on how to do reset

**Comment by Hackxiaoya** [comment]
@maximkulkin tks. I am from China, I still can't understand the specific example, I will check it again.
