### ISSUE TITLE
Wifi connectivity on ESP32

### ISSUE THREAD

**Issue by kunjal83** [maximkulkin/esp-homekit-demo#250]
Hi @maximkulkin, 

On ESP8266 we have wifi connectivity  library which allows connectivity in case of changed wifi creds. 
Can we use the same library on ESP32? 
From my basic knowledge, I think, I will need to get the install Free-RTOS to use this lib. Is my assessment correct? 

Thanks,
Kunjal

**Comment by maximkulkin** [comment]
Ehh.. there is so much wrong about that question I do not know even where to start.

Short answer: my esp-wifi-config library does not support ESP32.

**Comment by kunjal83** [comment]
Right!!! Guess, we will need to build something that supports ESP32. 
Thanks :)
