### ISSUE TITLE
Need help with DHT sensor

### ISSUE THREAD

**Issue by konifer44** [maximkulkin/esp-homekit-demo#253]
Hi guys, I know that dht.h comes with esp-open-rtos as an extra library, but Im new and I don't really know how to use external library, any step by step help here 😊?

**Comment by maximkulkin** [comment]
Here is an example of a thermostat that uses DHT sensor: https://github.com/maximkulkin/esp-homekit-demo/blob/master/examples/thermostat/thermostat.c#L177-L211
