### ISSUE TITLE
error with: git submodule update --init --recursive

### ISSUE THREAD

**Issue by renandw** [maximkulkin/esp-homekit-demo#254]
Hello guys, I'am having trouble when doing Initialize and sync all submodules (recursively):

~/projects/esp-homekit-demo$ git submodule update --init --recursive
fatal: index file smaller than expected
Failed to recurse into submodule path 'components/esp-8266/cJSON/cJSON'
fatal: index file smaller than expected
fatal: index file smaller than expected
fatal: index file smaller than expected
Failed to recurse into submodule path 'components/esp-8266/cJSON'
Failed to recurse into submodule path 'components/esp-8266/led-status'
Failed to recurse into submodule path 'components/esp-8266/qrcode'
Failed to recurse into submodule path 'components/esp-8266/wifi_config'

Any one having this trouble?
thanks

**Comment by kenthinson** [comment]
Are you on Mac? I couldn’t get it working normally. I ended up using the docer instructions. Then it was all fine.

**Comment by maximkulkin** [comment]
Try removing your working copy and clone whole repository again.

**Comment by renandw** [comment]
Thanks. E redo all the process and it is working. Thanks
