### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by Kristian8606** [maximkulkin/esp-homekit-demo#255]
hello I built two thermostats with a display and three buttons from the examples of Maxim When I plug a device into the socket, one thermostat resets my configuration and I have to add it from the beginning.
If I add buttons via three tasks, I have no reset, but I have too many tasks and I cannot connect every time.

**Comment by AchimPieters** [comment]
Did you made two identical thermostats? I believe that you need to make them unique.

**Comment by Kristian8606** [comment]
I set the GPIO_INTTYPE_EDGE_NEG interruptions  and the restart is gone and the thermostats are stable for now
 
![67122458-86f59100-f1f6-11e9-829b-fd31034779b0](https://user-images.githubusercontent.com/34716572/67224815-b72d7180-f43a-11e9-8a0b-32ffa2fac312.jpg)

**Comment by maximkulkin** [comment]
You probably have your buttons active state different from what was set up in the code.

**Comment by Kristian8606** [comment]
I use this connection scheme

![ZirYP](https://user-images.githubusercontent.com/34716572/67268625-99552080-f4bd-11e9-8cc9-522b05edd938.jpg)

**Comment by Kristian8606** [comment]
previously i used your example for buttons with the same connection scheme
but i got strange esp behavior and reset.
 am i doing something wrong?

**Comment by AchimPieters** [comment]
@Kristian8606 look at this: https://github.com/maximkulkin/esp-button

**Comment by maximkulkin** [comment]
Yeah, look at that. Obviously your case is “active low”, but that example was designed for “active high” case.
