### ISSUE TITLE
Color temperature behaviour in RGBW light

### ISSUE THREAD

**Issue by HomeACcessoryKid** [maximkulkin/esp-homekit-demo#26]
Reminder to myself to implement Color Temperature in the RGBW bulb example
(sorry to abuse an issue as a reminder tracker ;-)

**Comment by renssies** [comment]
For anyone who does not know about this, iOS 11.2.5's home app finally sends the Color temperature when adjusting the Color temperature in the home app. It no longer only sends hue and saturation to mimic a color temperature. 

I did some more testing with the HomeKit accessory simulator. And I found that in order for color temperature or color to behave correctly in the home app you should set the characteristic you are not changing to 0. 

So when setting Hue and Sat, you should set Color Temperature to 0. When setting Color Temperature, you should set Hue and Sat to 0. 

The home app still has some visual glitches when using it, but it works and it's better than having the weird "Color Temperature" that the Home app generates based on Hue and Sat
