### ISSUE TITLE
MagicHome led strip RGBW

### ISSUE THREAD

**Issue by toshibochan** [maximkulkin/esp-homekit-demo#262]
Thank you for developing.
Is possible to add MagicHome led strip RGBW?

**Comment by toshibochan** [comment]
You have YouTube for tutorial for installation?

**Comment by maximkulkin** [comment]
> You have YouTube for tutorial for installation?

Ahaha, no I do not.

**Comment by toshibochan** [comment]
I see you have RGB MagicHome version. Is possible to add RGBW?

**Comment by maximkulkin** [comment]
I pretty sure it is possible

**Comment by Kristian8606** [comment]
@maximkulkin I modified your LED_Strip example to achieve a smoother color change but since I'm a beginner my code looks awful.  If you have the time, is it possible to improve it?
