### ISSUE TITLE
SONOFF iFAN03 WiFi Ceiling Fan&Light Controller

### ISSUE THREAD

**Issue by toshibochan** [maximkulkin/esp-homekit-demo#268]
Is possible to make SONOFF iFAN03 WiFi Ceiling Fan&Light Controller?

https://www.amazon.com/dp/B07TRTG8PS/ref=cm_sw_r_cp_api_i_XbAWDbMRXFWCD

**Comment by toshibochan** [comment]
You can make for us?

**Comment by maximkulkin** [comment]
No, I do not do that

**Comment by toshibochan** [comment]
Where you get the codes from?

**Comment by maximkulkin** [comment]
I dream them myself
