### ISSUE TITLE
How to add multiple buttons?

### ISSUE THREAD

**Issue by toshibochan** [maximkulkin/esp-homekit-demo#270]
How to add multiple buttons in the button example?

**Comment by AchimPieters** [comment]
@toshibochan Maybe this will help: https://github.com/maximkulkin/esp-button

**Comment by toshibochan** [comment]
@AchimPieters this example only have one button in one esp. I want multiple buttons in one esp.

**Comment by AchimPieters** [comment]
@toshibochan in the sample you can see how it's done:  esp-homekit-demo/examples/sonoff_dual_blinds/main.c

**Comment by toshibochan** [comment]
Thanks @AchimPieters i will take look
