### ISSUE TITLE
sonoff_dual_blinds

### ISSUE THREAD

**Issue by okanduzyel** [maximkulkin/esp-homekit-demo#271]
sonoff_dual_blinds example has a problem. Up-down buttons don't work correctly.

**Comment by AchimPieters** [comment]
Uwe these buttons: https://github.com/maximkulkin/esp-button

**Comment by okanduzyel** [comment]
I use exactly these buttons with that schematics (with pull up resistor)

**Comment by AchimPieters** [comment]
What do they do, or not do?

**Comment by okanduzyel** [comment]
up button = open
down button = close.

Down button never works, Up button works wrong. When curtain closed, up button doesn't response. When curtain opened, up button tries to open where opened curtain.

Gpio settings are same with example. Lolin v3 board are new. I don't think it has any problem. 

If you have esp device, try it, you will see what I mention.

**Comment by AchimPieters** [comment]
well I have already: [https://github.com/AchimPieters/ESP8266-HomeKit-Blinds](https://github.com/AchimPieters/ESP8266-HomeKit-Blinds)
and it works just fine. Try my code?

**Comment by okanduzyel** [comment]
Now, I am at business trip. Maybe next week, I will try your code @AchimPieters

**Comment by okanduzyel** [comment]
> well I have already: https://github.com/AchimPieters/ESP8266-HomeKit-Blinds
> and it works just fine. Try my code?
> 
> btw: It's not a good idea to use pin nine, see my blog here:https://www.studiopieters.nl/esp8266-pinout/

Your example is definitely work! Thank you @AchimPieters

**Comment by toshibochan** [comment]
@AchimPieters the button is active high or low?

**Comment by AchimPieters** [comment]
@toshibochan  read this: https://github.com/maximkulkin/esp-button
