### ISSUE TITLE
build warning

### ISSUE THREAD

**Issue by mengds2016** [maximkulkin/esp-homekit-demo#273]
Success build ,but have some warning.

In file included from /home/esp-homekit-demo/components/common/wolfssl/wolfssl-4.1.0/wolfssl/ssl.h:33:0,
                 from /home/esp-homekit-demo/components/common/homekit/src/crypto.c:4:
/home/esp-homekit-demo/components/common/wolfssl/wolfssl-4.1.0/wolfssl/wolfcrypt/settings.h:669:0: note: this is the location of the previous definition
         #define XREALLOC(p, n, h, t) wolfSSL_Realloc((p), (n))
 ^
CC /home/esp-homekit-demo/components/common/homekit/src/server.c
In file included from /home/esp-homekit-demo/components/common/wolfssl/wolfssl-4.1.0/wolfssl/wolfcrypt/hash.h:29:0,
                 from /home/esp-homekit-demo/components/common/homekit/src/server.c:26:
/home/esp-homekit-demo/components/common/wolfssl/wolfssl-4.1.0/wolfssl/wolfcrypt/types.h:295:0: warning: "XREALLOC" redefined [enabled by default]
         #define XREALLOC(p, n, h, t) realloc((p), (n))

**Comment by maximkulkin** [comment]
It’s fine, disregard that
