### ISSUE TITLE
Question: Suggested scenes when pairing accessory

### ISSUE THREAD

**Issue by peros550** [maximkulkin/esp-homekit-demo#278]
I recently bought a Yeelight color bulb which started to support homekit after a firmware update. 
In order to add the bulb to Home app, you needed to use the Yeelight app which has an "Add to Home" button. The button seems to trigger an iOS API that starts the pairing process. 

After you have chosen room, during the pairing process, there is one additional step in which iOS asks to add your new accessory in the list of suggested scenes [see example](https://media.idownloadblog.com/wp-content/uploads/2018/09/add-scenes.jpg) 

I was wondering if there is something we could do in the definition of our accessories to have same suggestion during pairing. 

Thanks in advance,

**Comment by maximkulkin** [comment]
I think this is how it's done in iOS 13 - they ask for a scenes to include accessory in.
