### ISSUE TITLE
Window covering always on opening state

### ISSUE THREAD

**Issue by kiralikbeyin** [maximkulkin/esp-homekit-demo#280]
When i push the (up/down) button, homekit always show "opening" and never shows %xx open untill i set a new value from homekit screen.

````
position_state.value.int_value = POSITION_STATE_STOPPED; 
homekit_characteristic_notify(&position_state, position_state.value);
````
I think this code doesnt work for me, any one else?

**Comment by toshibochan** [comment]
Same for me

**Comment by kiralikbeyin** [comment]
@maximkulkin

**Comment by maximkulkin** [comment]
@kiralikbeyin What do you expect from me? You didn't even mention which firmware it is.

**Comment by maximkulkin** [comment]
Guys, guys, this is not my firmware, somebody contributed it. I do not know what is happening there. If you have ideas on how to improve it, you're welcome to contribute.

**Comment by konifer44** [comment]
Im using it and everything its working. I modify code in some places to add stepper motor support and hall sensor to detect full opened window covering and ensure it will never lost position in case power loss.

**Comment by toshibochan** [comment]
@konifer44 you can share your code?

**Comment by konifer44** [comment]
What ESP are You using?

**Comment by toshibochan** [comment]
I’m not sure yet. What you using? Can you take pictures of you setup?

**Comment by konifer44** [comment]
Are you using ESP32 or ESP8266

**Comment by toshibochan** [comment]
I don’t have yet. What is better ESP32 or ESP8266?

**Comment by konifer44** [comment]
ESP32 is more powerful😊
