### ISSUE TITLE
anyone have Sonoff mini Homekit firmware?

### ISSUE THREAD

**Issue by toshibochan** [maximkulkin/esp-homekit-demo#284]
anyone have Sonoff mini Homekit firmware?

**Comment by peros550** [comment]
It would be nice to know how to load firmware using Sonoff DIY firmware change tool

**Comment by toshibochan** [comment]
I find this one but give me error to build the firmware. And is a lot difference of sonoff-basics

https://github.com/maccoylton/esp-homekit-sonoff-mini

**Comment by maccoylton** [comment]
The build error is I suspect the way you have set up your build environment. Checkout the Wiki I just added for instructions to install pre-built firmware.

**Comment by maccoylton** [comment]
@peros550 the mini uses a different boot loader, so to my knowledge no one has figure out how to replace that OTA with Sonoff DIY tools. I have successfully flashed three by hard wiring with my firmware and they work great

**Comment by toshibochan** [comment]
@maccoylton thanks your sonoff mini is working great!
https://github.com/maccoylton/esp-homekit-sonoff-mini/wiki
