### ISSUE TITLE
ESP8266 Lock Demo Admin Access Only 

### ISSUE THREAD

**Issue by Ammarjeddin** [maximkulkin/esp-homekit-demo#292]
Is there a way we can include the Access only by admin characteristic to the lock in the Lock demo for esp

**Comment by maximkulkin** [comment]
I think you can check if client that is executing a characteristic setter is an admin and choose to ignore set command if he’s not. You can use `homekit_client_is_admin()` for that. Not sure if HomeKit supports showing different permissions to clients based on whether they are admins or not.
