### ISSUE TITLE
Remote access ESP8266

### ISSUE THREAD

**Issue by d4rkmen** [maximkulkin/esp-homekit-demo#294]
The demo accessory (tried lightbulb and thermostat demo) seems unreachable using remote access (through homekit center like iPad/AppleTV)
Same time other my accessories works fine (using avahi-client for advertise)
Once the controller (iPhone) registering in local network - all works again
Any hints please?

**Comment by maximkulkin** [comment]
This works perfectly fine for me. Make sure your AppleTV/iPad is enabled as HomeKit hub and is in the same WiFi network as HomeKit accessories.

**Comment by d4rkmen** [comment]
Great to hear the thing should work. Now need to understand why it doesnt work for me.
May be I have to set hostname or anything else?


> AppleTV/iPad is enabled as HomeKit

Yes, my other accessories available. Only this ESP-based is not

**Comment by maccoylton** [comment]
FYI I run 20 or so ESP based device of various types and remote access works flawlessly

**Comment by d4rkmen** [comment]
ESP8266_RTOS example tested and remote access works! Still have pairing problems: 3-4 false tries to pair

**Comment by maccoylton** [comment]
@d4rkmen I have seen this also recently, we think it may be related to some memory management issue in recent version of esp-open-rtos, still investigating

**Comment by d4rkmen** [comment]
@maccoylton this log is by the latest ESP8266_RTOS_SDK build. But I had same expiriense by esp-open-rtos
