### ISSUE TITLE
Homekit Example sending infrared remote control?

### ISSUE THREAD

**Issue by marcelopalermo** [maximkulkin/esp-homekit-demo#299]
Hi,
First of all, thanks a lot for this homekit github. Simply fantastic!
Question: do you have any esp-homekit-demo example by using infrared remote control sending? I have already implemented it via Arduino Uno and infrared LED with proper infrared Arduino libraries. I'm facing difficulties to implement a similar solution under esp-homekit-demo. I don't know whether there is any Infrared library I can include.

Any sample code will be very helpful.

Thanks
Regards
Marcelo

**Comment by maximkulkin** [comment]
This is my implementation of AC controller: https://github.com/maximkulkin/esp-ir-thermostat. I wrote my own IR library, which works pretty well for my purposes.

**Comment by marcelopalermo** [comment]
Thanks so much. I will download it. Best regards!
