### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by Kristian8606** [maximkulkin/esp-homekit-demo#300]
Hi maximkulkin is it possible to add an example with bluetooth on esp32
for example, one of these

https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/esp_ble_mesh

**Comment by maximkulkin** [comment]
esp-homekit does not work over bluetooth

**Comment by Kristian8606** [comment]
I had in mind whether it was possible to receive temperature data via bluetooth instead of using the DHT library.

**Comment by Kristian8606** [comment]
https://www.youtube.com/watch?v=Wef_bWNC2rY

**Comment by Kristian8606** [comment]
https://youtu.be/Wef_bWNC2rY

**Comment by lrusnac** [comment]
@Kristian8606 try searching for a ble library for freeRTOS, but as far as I remember the esp32 had issues in using both the bluetooth and wifi at the same time, they share the same radio, so it's one at a time, this might create some annoyances but should be possible if you use some semaphores and keep it always on wifi mode and once in a while switch to bluetooth to get the temperature and go back to wifi.
it might be a bit of work to get it right, so good luck :) but share with us if you manage to do it
