### ISSUE TITLE
ESP8266 (Docker): Cannot flash because files cannot be found

### ISSUE THREAD

**Issue by barning** [maximkulkin/esp-homekit-demo#306]
It seems that the code will fail if there are spaces in the disk name.
The files are there and Docker is running. If I copy the complete file path in the variables as a string, most of the files are found.

**Comment by lrusnac** [comment]
https://github.com/maximkulkin/esp-homekit-demo/issues/288

**Comment by maximkulkin** [comment]
Just use disk names without spaces.
