### ISSUE TITLE
cannot build following docker instructions (macOS catalina)

### ISSUE THREAD

**Issue by mentaluproar** [maximkulkin/esp-homekit-demo#335]
I followed directions to build and flash the LED example but when i get to the flashing step, I get the following error:

Makefile:13: /common.mk: No such file or directory
make: *** No rule to make target `/common.mk'.  Stop.

**Comment by maximkulkin** [comment]
You need to set SDK_PATH environment variable pointing to esp-open-rtos checked out on your host machine. This is ugly part of the whole approach because Docker does not handle passing devices to containers properly (otherwise you could flash from inside container).
