### ISSUE TITLE
Can you provide more demos

### ISSUE THREAD

**Issue by CHNleing** [maximkulkin/esp-homekit-demo#336]
I want to learn more examples

**Comment by rillhu** [comment]
> I want to learn more examples
I think current repo provides sufficient ESP8266 examples.  Do you mean ESP32 examples? if you want to see maore ESP32 examples, you could refer to my repository (although I used another homekit library from younghyunjo, you could still find useful examples from my repo).
You can find my [esp32-homekit](https://github.com/rillhu/esp32-homekit) here.

**Comment by CHNleing** [comment]
I want to know more types of cases, such as air conditioners, windows, thermostats

**Comment by maximkulkin** [comment]
@CHNleing download the HomeKit Specification and indulge yourself.

**Comment by CHNleing** [comment]
@maximkulkin Thank you very much, I found Homekit Accessory Protocol Specification from Apple official website.
I am trying to read it.
