### ISSUE TITLE
Lost wifi pass

### ISSUE THREAD

**Issue by borcares** [maximkulkin/esp-homekit-demo#340]
Hi, 
I have a problem, 
I flashed the example off sonoff basic in a nodemcu v3, and the problem is that when I run a automation in home app, for example turn on at 7:00 pm, the light turn on and turn off, and the nodemcu lost the wifi password like a hard reset of the module... I have to config the wifi password and add the device to homekit again..

Anyone can help?

Thanks.

**Comment by Kristian8606** [comment]
I encountered a similar problem when flash the same example of nodemcu.  The problem was that the gpio was not connected to a button and had no pul-up resistor and restarted even when touched.  set the gpio button to 0 and the problem may disappear.
