### ISSUE TITLE
Does Homekit devices cost Internet Data?

### ISSUE THREAD

**Issue by kalindud** [maximkulkin/esp-homekit-demo#342]
Hi,
 I have an issue with homekit devices. I have used 2 homekit devices always running. a LIGHT and a FAN. 
does this mean that Im constantly consuming Internet Data?
cuz my Data downloads are showing 1 - 2 GB downloads each day even when all my other devices are off.

**Comment by maximkulkin** [comment]
No, devices do not connect to internet on their own, unless you have something like LCM (life-cycle manager), but even then checking for (or even downloading) a new firmware version can not account for gigabytes per day.
