### ISSUE TITLE
Adjustment in program required for Sonoff Basic R3

### ISSUE THREAD

**Issue by sanilsdevan** [maximkulkin/esp-homekit-demo#352]
Sonoff basic R3 (the latest sonoff basic) has wifi indicator led on GPIO13 and also another indicator led connected to relay on GPIO12. Is there any chance that the program can be modified so that the wifi indicator led turns off (or keeps blinking) if the device gets disconnected from wifi network? Also, the wifi indicator keeps on blinking at the initial stage until the device is configured & gets connected to the wifi network for the first time..thanks

![image](https://user-images.githubusercontent.com/36995748/82708543-8e4eb280-9c8f-11ea-8f35-b7c62d2150ae.png)

**Comment by maximkulkin** [comment]
I have published [my internal version](https://github.com/maximkulkin/esp-sonoff-outlet) of Sonoff S20/S26 firmware, check it out.

**Comment by sanilsdevan** [comment]
Thank You so much
