### ISSUE TITLE
Sonoff_Basic_PWM change icon

### ISSUE THREAD

**Issue by kalindud** [maximkulkin/esp-homekit-demo#354]
Hello,
 I need to control a FAN using the sonoff PwM....
how Can I change the Icon from a light bulb to a fan????

thank you!

**Comment by maximkulkin** [comment]
You need to change LIGHTBULB service to FAN2 service, ON characteristic to ACTIVE (note that later takes values 0 and 1 instead of true and false for former characteristic) and BRIGHTNESS characteristic to ROTATION_SPEED (effectively converting accessory into a FAN accessory).
