### ISSUE TITLE
Shelly Dimmer with sonoff_basic_pwm code

### ISSUE THREAD

**Issue by Jojoander03** [maximkulkin/esp-homekit-demo#355]
I’m interested in sonoff_basic_pwm example, is it possible to flash that example on Shelly dimmer?

**Comment by lukasa1993** [comment]
is sonoff_basic_pwm dimmer? i am looking for sample to flash dimmer with esp8266

**Comment by maximkulkin** [comment]
It is a light dimmer, but it says it talks to a daughter board with PWM and that board I assume does the dimming. Not sure how Shelly Dimmer does it's dimming.
