### ISSUE TITLE
two touch switch motor homekit device

### ISSUE THREAD

**Issue by ageorgios** [maximkulkin/esp-homekit-demo#36]
I am trying to implement a two touch switch device that controls a motor. I am only starting though. I plan to use a Sonoff T1 2CH EU

I am trying to figure out how to implement the interlocking between the two buttons.
To clarify, AT NO TIME should both switches be ON at the same time, because this may damage the motor. So it is crucial that there will be no possibility such a thing to happen.

I am wondering if such code works so as to exclude this kind of situation
```
void button_callback(uint8_t gpio_num, button_event_t event) {
    taskENTER_CRITICAL();
    if (mutex == 0) {
        mutex = 1;
        taskEXIT_CRITICAL();
        if (gpio_num == button1_gpio) buttonUP_handle(4000);
        else if (gpio_num == button2_gpio) buttonDOWN_handle(4000);        
        mutex = 0;
    }
    else {
        taskEXIT_CRITICAL();
        printf("race condition, doing nothing");
    }
}
```

**Comment by marcoskirsch** [comment]
> To clarify, AT NO TIME should both switches be ON at the same time, because this may damage the motor. So it is crucial that there will be no possibility such a thing to happen.

I don't think software is the way to ensure this. Most relay you'd buy to control your motor already have 3 terminals - common, and two that alternate between on and off. Does the Sonos not provide the 3 terminals? Maybe look for something else.

**Comment by ageorgios** [comment]
No it doesn't, both switches can be on.

**Comment by maximkulkin** [comment]
@ageorgios Your question is about how to use multitasking synchronization properly, right? In your case it would be sufficient to use binary semaphore:

```c
#include <semphr.h>

static SemaphoreHandle_t mutex = NULL;

void user_init() {
    mutex = xSemaphoreCreateBinary();
    xSemaphoreGive(mutex);
    // ...
}

void button_callback(uint8_t gpio_num, button_event_t event) {
    if (xSemaphoreTake(mutex, 0) == pdTrue) {
        // Got mutex, proceed with processing
        // ...
        xSemaphoreGive(mutex);
    }
}
```
