### ISSUE TITLE
Multiple accessories in one device

### ISSUE THREAD

**Issue by ihrfelt** [maximkulkin/esp-homekit-demo#360]
Hello,

I am trying to add two accessories to one device, but my code do not compile. This how i have defined homekit_accessory_t:

<img width="873" alt="Skärmavbild 2020-06-17 kl  22 15 36" src="https://user-images.githubusercontent.com/67070434/84945844-133eb780-b0e8-11ea-81d1-4ed91a455f11.png">

And this is the only errormessage i get:

<img width="689" alt="Skärmavbild 2020-06-17 kl  22 15 03" src="https://user-images.githubusercontent.com/67070434/84945804-ff935100-b0e7-11ea-99e8-8cfdaf5abba3.png">
Ive been stuck for a while, if anyone have any suggestions i would be very thankful.

Fredrik

**Comment by maximkulkin** [comment]
At line 298 you have NULL which is not supposed to be there.
