### ISSUE TITLE
Integration with ESP Mesh

### ISSUE THREAD

**Issue by arpadgabor** [maximkulkin/esp-homekit-demo#362]
I'm working on a few devices connected through ESP-MESH. Wondering if there is any way of integrating this with a mesh network. Not looking for direct integration in the library.

The problem I am facing is that only the root node is accessible by the external network (i.e. home wifi). Is there any way to intercept HAP messages and redirect them? Or maybe programatically add accessories?

**Comment by maximkulkin** [comment]
If you want your accessories available via ESP-MESH, best bet is to create a bridge device that will talk both WiFi and ESP-MESH and which will expose all ESP-MESH devices as HomeKit accessories.
