### ISSUE TITLE
It's here! Apple_HomeKit_ADK from espressivo

### ISSUE THREAD

**Issue by konifer44** [maximkulkin/esp-homekit-demo#371]
https://www.espressif.com/en/news/ESP_Apple_HomeKit_ADK

**Comment by peros550** [comment]
This is news for esp32 devices but for esp8266 no, they seem to point to a library which is a port of esp-homekit.

**Comment by konifer44** [comment]
You can use project from maximkulkin on Esp32. You have in examples folder👋🏼
