### ISSUE TITLE
ESP32 - Toggle

### ISSUE THREAD

**Issue by kunjal83** [maximkulkin/esp-homekit-demo#372]
Hi all,

I am trying to implement the Toggle example on my ESP32, however, it seems the input toggle isnt getting detected at all. 

I have tried with External and internal pull up resistors however, in both the cases, input pins (Pin # 12 and 27) allows shows 0 Volts leading to no change being detected. --> This is when I am connecting this pin to 3.3v via a pull up (10K / 4.7K) / NOT Gate (to allow drain) OR to Ground terminal. 
Has anyone encountered any such trouble before? 

I tried implementing the ISR event handler and with this it works fine. 

Code for implementing the toggle is exactly identical to the one in Example for Toggle. 

Any pointers is much appreciated. 

Thanks.

**Comment by renandw** [comment]
Try to update your code with this library: https://github.com/maximkulkin/esp-button
