### ISSUE TITLE
FAN2 example with relays for speed

### ISSUE THREAD

**Issue by cab113** [maximkulkin/esp-homekit-demo#385]
Hi All, question 

Is there a example for FAN2 accessory, where the speed can turn on 3 individual relays on a 3 speed fan?

**Comment by toshibochan** [comment]
Look this https://github.com/RavenSystem/esp-homekit-devices/wiki/Devices-Database

**Comment by cab113** [comment]
Thanks @toshibochan. I have used ravencore before, im building a multi- accessory with temperature and ranven core doesnt support what im after. I have worked out how to set up fan2 accessory with rotational speed, im stuck it the part where to and how to assign my 3 speeds to three individual relays.
