### ISSUE TITLE
Proposal: Create Discussion Group for "esp-homekit"

### ISSUE THREAD

**Issue by brianhanifin** [maximkulkin/esp-homekit-demo#39]
Is there interest in creating a Facebook group (or Reddit)? That way the users could support each other while the developer(s) can spend more time focusing on bugs and improvments. If someone is unsure if something should be reported as a bug it could be discussed there first. 

It could also be a place to brag about the interesting and creative ways you have put this library to use! 😉

**Comment by brianhanifin** [comment]
Here is a link to one I have started. Join if you want, or tell me this is a bad idea and why I should shut it down. 😀 

https://www.facebook.com/groups/2057393107867342/

**Comment by renssies** [comment]
I know that some members might be concerned with privacy, they won't join a facebook group.

So I made a Subreddit: https://www.reddit.com/r/ESPHomeKit/. Reddit is also better at handling code blocks in comments and posts.

**Comment by brianhanifin** [comment]
@renssies That's great! Thank you for doing that, I just joined up.

**Comment by AdySan** [comment]
I’d also recommend gitter. Works great with GitHub logins.

**Comment by brianhanifin** [comment]
@AdySan I used Gitter a few times when I contributed to an open source project a few years ago. If I remember correctly it is a nice chat interface for developers working on a project together. But a nice reddit is a nice because it becomes a searchable knowledgeable.

**Comment by ageorgios** [comment]
+1 for Gitter

**Comment by renssies** [comment]
I have created a gitter as well: https://gitter.im/ESP-HomeKit/Lobby
