### ISSUE TITLE
Is it possible to determine the name of a homekit service that has been changed in home app 

### ISSUE THREAD

**Issue by Azmatron** [maximkulkin/esp-homekit-demo#390]
For example, if I name a homekit service "door1" and then rename it "backdoor" in the home app, is there a way to capture/retrieve this within the API?

**Comment by maximkulkin** [comment]
In general case - NO. Some services include "Configured Name" characteristic which in fact is stored inside accessory (and shared across all clients), e.g. INPUT SOURCE service (which is a satellite service for TELEVISION service) has CONFIGURED_NAME characteristic.
