### ISSUE TITLE
homekit rgb characteristic

### ISSUE THREAD

**Issue by mikimause9** [maximkulkin/esp-homekit-demo#391]
Hi,
I am new at HomeKit, and I am trying to make an Rgb light based on HAP.
I did a dimmer, and I want to make rgb light, but I don't know how.
Can you help me?

**Comment by AchimPieters** [comment]
@mikimause9 Here you go: https://github.com/maximkulkin/esp-homekit-demo/blob/master/examples/magic_home_strip/magic_home.c

**Comment by mikimause9** [comment]
Thanks
