### ISSUE TITLE
TV Support Example

### ISSUE THREAD

**Issue by joaodforce** [maximkulkin/esp-homekit-demo#395]
I making an adapter to control my LG TV via it's serial port. I got a hold of the protocol it uses, and It is possible to control anything trough it. Change volume, input. directions etc...

However Im not familiar with the ESP-Homekit SDK yet, Im studying it and the examples, however there is no example of setting the acessory to show as an actual TV on the home App. I've gotten the core methods working, I just need to bing the correct services and characteristics to make it appear right.

If someone can give me a light on the matter I would gladly make a PR to add the TV accessory as an example.

**Comment by maximkulkin** [comment]
Check [this](https://github.com/maximkulkin/esp-ir-tv) repository, it's a TV accessory that controls TV through IR commands.

**Comment by andrei-gavrila** [comment]
Here is an example on using the input sources - that can be freely renamed in Homekit - to set up a list of favorite channels for easy switching: https://github.com/maximkulkin/esp-ir/issues/11

More details are available in the post.

@maximkulkin BTW, a reply to that issue would be highly appreciated 😛

**Comment by joaodforce** [comment]
omg! this is perfect! thanks, I'll be working with the provided examples.

**Comment by pocketscience** [comment]
> I making an adapter to control my LG TV via it's serial port. I got a hold of the protocol it uses, and It is possible to control anything trough it. Change volume, input. directions etc...
> 
> However Im not familiar with the ESP-Homekit SDK yet, Im studying it and the examples, however there is no example of setting the acessory to show as an actual TV on the home App. I've gotten the core methods working, I just need to bing the correct services and characteristics to make it appear right.
> 
> If someone can give me a light on the matter I would gladly make a PR to add the TV accessory as an example.

@joaodforce Can you post a link to the LG protocol documentation please? Thanks.

**Comment by joaodforce** [comment]
@pocketscience  Sure thing, I used the one from this site

https://support.justaddpower.com/kb/article/36-lg-rs232-control/

I also have this PDF, but I don't remember where I got it from, I think I printed from some website.

[RS-232C - LG TV Control.pdf](https://github.com/maximkulkin/esp-homekit-demo/files/5354801/RS-232C.-.LG.TV.Control.pdf)

I don't know how many LG TVs share this protocol however.
