### ISSUE TITLE
Create homekit bridge

### ISSUE THREAD

**Issue by FFTSolution** [maximkulkin/esp-homekit-demo#396]
sorry, I can Solve it !
thanks for reply !!

**Comment by maximkulkin** [comment]
Let's first define what we are trying to achieve here.

**Comment by FFTSolution** [comment]
i want to create homekit Bridge, so I want use Zigbee/Z-wave for send data from Sensor to Homebride !

**Comment by maximkulkin** [comment]
Usually what happens is your bridge device exposes itself as an accessory with ID=1 and just an ACCESSORY_INFO service (and accessory category=2 (homekit_accessory_category_bridge)). All bridged devices are exposed as additional accessories, each have services corresponding to accessory type.
