### ISSUE TITLE
Pairing multiple devices?

### ISSUE THREAD

**Issue by ZweiEuro** [maximkulkin/esp-homekit-demo#412]
After initially paring one device, the homekit device doesn't show up for other homekit clients. 
Looking at the code it's saying that it already as an admin pairing, can only one homekit device be paired?

**Comment by maximkulkin** [comment]
Initial (admin) pairing can be done only once. Then admin controller invites other people into the Home and when they accept invitations it adds more pairings through a special pairing management API.

**Comment by ZweiEuro** [comment]
Ah ok, so the admin has to be in the same network for the time being?

**Comment by ZweiEuro** [comment]
How can such an invite be sent?

**Comment by rottenhowler** [comment]
In Home app select Home tab at the bottom, then press Home icon in the top left corner, in the popup menu select "Home Settings",  then in "People" section click "Invite People..." and enter people emails (not sure if it needs to be Apple IDs or not).

**Comment by ZweiEuro** [comment]
ok, thanks !
