### ISSUE TITLE
Motion sensor becoming non responsive

### ISSUE THREAD

**Issue by AR-Tawil** [maximkulkin/esp-homekit-demo#429]
Hi, I'm using your motion sensor code and it works perfectly. However, I noticed that the board needs resetting every two days or it will go into a No Responsive state?!!!

**Comment by AchimPieters** [comment]
@AR-Tawil without information it is difficult to say where things are going wrong?

**Comment by maximkulkin** [comment]
Right, it would be nice to include some more information next time:
* which board is this
* which SDK and version did you use
* was the accessory pingable while being unresponsive
* what was the output of `dns-sd -B _hap._tcp local` (natively on Mac or through Bonjour SDK downloadable from [developer.apple.com/opensource/](https://developer.apple.com/opensource/) on Windows)
* accessory logs if available
