### ISSUE TITLE
Apple Silicon - M1 (Pro/Max/Ultra)

### ISSUE THREAD

**Issue by nikomaxi** [maximkulkin/esp-homekit-demo#431]
Can anybody tell me, if this is working on a MacBook Pro with Apple Silicon M1? 

Thanks!

**Comment by maximkulkin** [comment]
I'm developing on M1 Max, works fine. I'm using Docker setup for ESP8266 and ESP-IDF for ESP32.

**Comment by kiralikbeyin** [comment]
Can I use the repo with ESP-IDF latest version 5.2? Which ESP-IDF version do you use? @maximkulkin

**Comment by maximkulkin** [comment]
@kiralikbeyin eps-homekit was ported to ESP-IDF v5.x, but that support wasn't merged into master yet as there's a lot of work testing it on different frameworks and versions. You can try using it: just use [esp-idf-v5](https://github.com/maximkulkin/esp-homekit/tree/esp-idf-v5) branch.

**Comment by kiralikbeyin** [comment]
@maximkulkin 
I tried running it with the esp-idf-v5 branch for a few days, but I couldn't succeed.
Finally, I gave up when I started getting compiling errors regarding wolfssl.
Are there different installation instructions for v5?

**Comment by kiralikbeyin** [comment]
@maximkulkin 
https://github.com/maximkulkin/esp-homekit-demo/tree/master/components/common

I think a change has been made for idf v5 below, but the "homekit @ ab8a436" link does not open. 
https://github.com/maximkulkin/esp-homekit/tree/ab8a436b4d70ccda416943ef6bf61930d1db6049
