### ISSUE TITLE
unstable accessory

### ISSUE THREAD

**Issue by ageorgios** [maximkulkin/esp-homekit-demo#48]
hello I have created 
https://github.com/ageorgios/esp-homekit-motor

but I find the accessory quite unstable
in the log I have this when the accessory is marked unresponsive, I cannot understand the reason it is happening and when.

```
>>> homekit_client_process: [Client 6] Finished processing
>>> mdns_recv: pbuf too big
>>> HomeKit: [Client 5] Closing client connection
>>> homekit_client_process: [Client 6] Got 129 incomming data
>>> homekit_client_process: [Client 6] Decrypting data
>>> homekit_client_process: [Client 6] Decrypted 111 bytes, available 0
Decrypted data (111 bytes): "GET /characteristics?id=1.11,1.10 HTTP/1.1\x0D\x0AHost: ESP\\032Homekit\\032Motor\\03212\\0581C\\0584C._hap._tcp.local\x0D\x0A\x0D\x0A"
>>> HomeKit: [Client 6] Get Characteristics
>>> homekit_server_on_get_characteristics: Free heap: 23136
```

any ideas?

**Comment by renssies** [comment]
"No Response" is not related to what you see in this log, it is a problem with mDNS/Bonjour. Maxim is aware of issues with mDNS, but we have yet to find the solution. 

Try updating the esp-homekit submodule there was one change that might improve it for your network situation.

**Comment by ageorgios** [comment]
you are right! wasn't on latest commit! definitely improved!
