### ISSUE TITLE
Add Coprocessor i2c

### ISSUE THREAD

**Issue by jukorp** [maximkulkin/esp-homekit-demo#53]
Is it possible to connect mfi chip i2c -> esp8266?

![1491f862-6cc6-49aa-bbf4-7cf733841f20](https://user-images.githubusercontent.com/34451630/37862778-6ac29294-2f5b-11e8-88b4-4286e475d9d0.gif)

Part Number : MFI337S3959
Package : QFN 8-1 Pin, Apple Inc.
Shelf iPod, iPhone, iPad video / headphone / battery-related Apple (Apple) to decrypt ic:
APN337S3959
MFI337S3959
APN337S3957
MFI337S3957
MFI341S2159
MFI341S2257
MFI341S2592
MFI341S2748
MFI341S2159
MFI341S2161
MFI341S2162
APN337S3957
MFI341S2164
MFI341S500
MFI353S2429
MFI353S2430

Chips are sold on ebay and aliexpress.

**Comment by maximkulkin** [comment]
Probably yes, but we do not provide support for those.
