### ISSUE TITLE
Is using a static IP possible?

### ISSUE THREAD

**Issue by korstiaanS** [maximkulkin/esp-homekit-demo#66]
Hi,

Can you use a static IP instead of DHCP?
I already looked at the esp-open-rtos site but I don't find anything that works.
Can somebody help me to set this up?
Thanks.
Korstiaan

**Comment by maximkulkin** [comment]
Haven't tried that, but it looks like you need to do the following:
```c
#include <espressif/user_interface.h>


sdk_wifi_station_dhcpc_stop();

static struct ip_info my_ip = {
    .ip = IPADDR4_INIT_BYTES(192, 168, 0, 55),
    .netmask = IPADDR4_INIT_BYTES(255, 255, 255, 0),
    .gw = IPADDR4_INIT_BYTES(192, 168, 0, 1)
};
sdk_wifi_set_ip_info(STATION_IF, &my_ip);
```

**Comment by korstiaanS** [comment]
Hi,

No success.
I'm also asking at esp-open-rtos, see [https://github.com/SuperHouse/esp-open-rtos/issues/619](url)
