### ISSUE TITLE
Fallback system when pairing gets interrupted

### ISSUE THREAD

**Issue by korstiaanS** [maximkulkin/esp-homekit-demo#68]
I've created a small udp task that handles some commands in parallel to homekit.
One of my instructuctions that I can receive via an UDP packet is 'ERASE'. (I use PacketSender)
If my ESP receives this command I execute the following code:

```
uint8_t blank[4];
memset(blank, 0, sizeof(blank));
if (!spiflash_write(0x100000, blank, sizeof(blank))) {
    sprintf(responsebuf, "ERASE_ERROR");
}
else {
    sprintf(responsebuf, "ERASE_OK");
}
...

```
after that I send a RESTART command on my UDP link and this way all the homekit pairings are gone and I can start with a new pairing. This avoids getting stuck and reflash the ESP.
But it would be better if I could use the existing SPIFLASH_BASE_ADDR instead of 0x100000 or use homekit_storage_reset() but I don't know how I can get this inside my code? (What to include).
I'm not so familiar with these things.

**Comment by maximkulkin** [comment]
There is a public API that handles everything for you - `homekit_server_reset()`. Just do:
```c
#include <homekit/homekit.h>

homekit_server_reset();
```
