### ISSUE TITLE
Valid Values

### ISSUE THREAD

**Issue by medmile** [maximkulkin/esp-homekit-demo#7]
Haw can i set valid values for characteristic:
homekit_characteristic_t TARGET_HEATING_COOLING_STATE = {
    .type = HOMEKIT_CHARACTERISTIC_TARGET_HEATING_COOLING_STATE,
    .format = homekit_format_uint8,
    .permissions = homekit_permissions_paired_read
                 | homekit_permissions_paired_write
                 | homekit_permissions_notify,
    .min_value = (float[]) {0},
    .max_value = (float[]) {2},
    .min_step = (float[]) {1},
    0,
    1,
    2,
};

**Comment by maximkulkin** [comment]
That is not supported yet, but I'm working on it and should finish pretty soon. Stay tuned.

**Comment by maximkulkin** [comment]
Added support for valid-values and valid-values-range. Usage is like this:
```
homekit_characteristic_t TARGET_HEATING_COOLING_STATE = {
    .type = HOMEKIT_CHARACTERISTIC_TARGET_HEATING_COOLING_STATE,
    .format = homekit_format_uint8,
    .permissions = homekit_permissions_paired_read
    | homekit_permissions_paired_write
    | homekit_permissions_notify,
    .min_value = (float[]) {0},
    .max_value = (float[]) {2},
    .min_step = (float[]) {1},
    .valid_values = {
        .count = 3,
        .values = (uint8_t[]) { 0, 1, 2 },
    }
};
```
