### ISSUE TITLE
Question about thermostat

### ISSUE THREAD

**Issue by Kristian8606** [maximkulkin/esp-homekit-demo#73]
DHT22 will work with the thermostat?
And why, when I set the thermostat off, does the relay turn on?

**Comment by maximkulkin** [comment]
DHT22 should be supported.

For relay: you might have a different kind of relay which works in reverse.

**Comment by Kristian8606** [comment]
DHT_TYPE_DHT11 I replaced it with DHT_TYPE_DXT22 and the sensor worked perfectly.
The question remains how to turn the function of the relay from the code itself?

**Comment by pcsaito** [comment]
Just find the respective gpio_write call and reverse the second argument.

Example:
Change from
```
void heaterOn() {
    gpio_write(HEATER_PIN, false);
}
```

To
```
void heaterOn() {
    gpio_write(HEATER_PIN, true);
}
```

Don’t forget to reverse the “off” function as well.

**Comment by Kristian8606** [comment]
Thanks for the reply.
Now it works when I set the temperature higher than the current's, but there is another.
When the thermostat is plugged into the socket, the relay works and when I set the heater switches off and starts functioning as I want.

I mean, when I plug it in, I do not want it plugged in until I plug it in from the app.

I would be grateful to you if and with that's help.

**Comment by maximkulkin** [comment]
Obviously, you had to update initialization code with a reversed values as well. I have updated thermostat example to reuse `*On()` and `*Off()` functions so you only need to change it in one place. You can just rebase to latest code and it should work.

Closing issue. Feel free to reopen if you have any more questions.
