### ISSUE TITLE
No response after some time (days)

### ISSUE THREAD

**Issue by korstiaanS** [maximkulkin/esp-homekit-demo#74]
I have about 12 modules active for some weeks now and I have every few days one or more modules that shows `No response`. Even after long waiting, restart iPhone and/or Apple TV (homehub), the module will not work anymore in homekit.
When it says no response I can still ping it AND my own UDP tasks keeps working.
Via my UDP task I can remotly restart the module (using `sdk_system_restart();`).
And yes, after a restart the module works again in homekit.
My conclusion: something happens inside the homekit software on the module and can only be fixed by a restart.
What could be wrong?
Restart once every 24hrs to avoid getting stuck?

PS: These modules worked before homekit already for more than 6 months with my own protocol  without 1 interruption. So the hardware is fine.

**Comment by RavenSystem** [comment]
Use the latest version of HomeKit framework instead included in this repo.

**Comment by korstiaanS** [comment]
This homekit framework from this repo points to the latest Homekit framework isn't it?
There is no Homekit framework source here.

**Comment by RavenSystem** [comment]
Sorry, You arr right. This repo uses latest version of Homekit framework. To help you, it’s necessary that you provides logs.

**Comment by korstiaanS** [comment]
After further investigation it saw that, unlike I pulled it not to long ago, the homekit version was at an older version? How is that possible? After doing a separate pull of the homekit directory I saw:
`Updating 825e385..819ec9b`

So it was an older version?
Could that be the reason?
How must I upgrade it in the future?

**Comment by RavenSystem** [comment]
Try this from root of repo:
`git submodule update --recursive --remote`

**Comment by korstiaanS** [comment]
Ok, thanks!
