### ISSUE TITLE
Connection after wifi restart

### ISSUE THREAD

**Issue by medmile** [maximkulkin/esp-homekit-demo#8]
I test my device. And after my wifi router restart, ios can not connect to device. Can you help me?
This repeated:
{"characteristics":[{"aid":1,"iid":13,"value":22}]}
>>> client_send: Encrypting payload
>>> send_tlv_response: Sending TLV response
>>> tlv_debug: Got following TLV values:
>>> tlv_debug: Type 6 value (1 bytes): \x04
>>> homekit_client_task: Got 92 incomming data
>>> homekit_client_task: Decrypting data
>>> homekit_client_task: Decrypted 74 bytes, available 0
Decrypted data (74 bytes): "GET /accessories HTTP/1.1\x0D\x0AHost: Temperature\\032Sensor._hap._tcp.local\x0D\x0A\x0D\x0A"
>>> homekit_server_on_get_accessories: HomeKit Get Accessories
>>> homekit_server_on_get_accessories: Free heap: 10692
>>> send_json_response: Sending JSON response
Fatal exception (28):
epc1=0x4000bf80
epc2=0x00000000
epc3=0x40202578

0x40202578: sdk_system_pp_recycle_rx_pkt at /Volumes/cs/esp-open-sdk/esp-open-rtos/open_esplibs/libmain/user_interface.c:620

excvaddr=0x00000000
depc=0x00000000
excsave1=0x40002ad0
Registers:
a0 40002ad0 a1 3fffa4d0 a2  00000000 a3  fffffffc
a4  000000ff a5  0000ff00 a6  00ff0000 a7  ff000000
a8  0000001f a9  00000022 a10 00000002 a11 0000005c
a12 3fff4070 a13 3fffdb60 SAR 00000008

Stack: SP=0x3fffa4d0
0x3fffa4d0: 4021657d 3fffdb60 3fff4070 40216575

0x4021657d: send_json_response at /Volumes/cs/esp-open-sdk/esp-open-rtos/esp-homekit-demo/components/homekit/src/server.c:781

0x40216575: send_json_response at /Volumes/cs/esp-open-sdk/esp-open-rtos/esp-homekit-demo/components/homekit/src/server.c:780

0x3fffa4e0: 3fff3ff8 402354e0 000000c8 40230600

0x402354e0: homekit_characteristic_has_notify_callback at ??:?

0x40230600: cJSON_strdup at /Volumes/cs/esp-open-sdk/esp-open-rtos/esp-homekit-demo/components/cJSON/cJSON/cJSON.c:1200

0x3fffa4f0: 3fff1728 3fffdc98 3fffdb60 3fff3ff8
0x3fffa500: 00000000 3fffdb60 00000000 40217cb9

0x40217cb9: homekit_server_on_get_accessories at /Volumes/cs/esp-open-sdk/esp-open-rtos/esp-homekit-demo/components/homekit/src/server.c:1828

0x3fffa510: 3fffdc98 3ffe898c 3fffc4b0 3ffe8970
0x3fffa520: 3fff99f8 3fff4070 00000000 00000001
0x3fffa530: fffffffe 00000001 00000001 3fffa8c9
0x3fffa540: 00010000 3fffa8ca 3fff3ff8 40218909

0x40218909: homekit_server_on_message_complete at /Volumes/cs/esp-open-sdk/esp-open-rtos/esp-homekit-demo/components/homekit/src/server.c:2530

Free Heap: 2260
_heap_start 0x3fff1930 brk 0x3ffff854 supervisor sp 0x3ffffb00 sp-brk 684 bytes
arena (total_size) 57124 fordblks (free_size) 1576 uordblocks (used_size) 55548

ets Jan  8 2013,rst cause:2, boot mode:(1,6)

ets Jan  8 2013,rst cause:4, boot mode:(1,6)

wdt reset

**Comment by maximkulkin** [comment]
There seem to be problems in SDK a) handling loss of connectivity; b) restarting device after a crash.

Will keep looking into this.

**Comment by maximkulkin** [comment]
Ok, after reviewing stack trace again it looks like it was out of memory problem. So, after loosing and restoring connectivity to accessory iOS tried to reconnect and thus re-request accessory information which by that time was too memory hungry. The memory usage was greatly optimized since then.

I will close this for now. If you feel there is still a problem, feel free to reopen it.
