### ISSUE TITLE
What type and characteristics

### ISSUE THREAD

**Issue by supersjimmie** [maximkulkin/esp-homekit-demo#82]
I have a wallmount dimmer. It's a double dimmer with touch buttons. Those buttons are controlled over 433MHz. See my other "issue" where I am building communication with (e.g.) some other 433MHz devices.

Does anyone know what type/characteristics I could use for a dimmer with such buttons:
```
/---------------\
| [ 1 ]   [ 4 ] |
| [ 2 ]   [ 5 ] |
| [ 3 ]   [ 6 ] |
\---------------/
Dinner room:
1 = UP
2 = on/off
3 = DOWN

Main room:
4 = UP
5 = on/off
6 = DOWN

```
I have been experimenting with values from types.h  and characteristics.h  but still unable to find how to "create" such device.

**Comment by maximkulkin** [comment]
Obviously, you need a LIGHTBULB service with ON and BRIGHTNESS characteristics: ON will turn light bulb on/off and BRIGHTNESS will allow controlling.. well.. brightness. You can create two LIGHTBULB services in a single accessory.

**Comment by supersjimmie** [comment]
Thanks yes that sounds obvious. :)
But the buttons are not like lightbulbs, because they are stateless(?) here.  You tip it, instead of switching it (I'm not sure how to explain). Same for the brightness, you don't set brightness to a specific value like 60%, you can only tip on the up/down buttons without knowing the current/new value (also stateless).

I've tried to add a characteristic "stateless programmable switch, also called a button", under a type "homekit_accessory_category_programmable_switch", but then the iPhone says that it needs a home-app to use this accessory (not sure about the exact term because my ios is Dutch).

**Comment by supersjimmie** [comment]
Perhaps it's simple enough for me if you can tell me how to make the button on the iphone turn off after I tap it (now the button toggles light/dark but I need it to stay dark after each tap).

Then next will be finding a way to create some kind of grouping/layout for those 6 buttons.

**Comment by renssies** [comment]
Have a look at the HomeKit Specification. It is what this library is based on. You can download it here with a free developer account: https://developer.apple.com/homekit/specification/

It will explain what a programmable switch is and might give you an inspiration for the brightness up/down buttons.

**Comment by supersjimmie** [comment]
I guess this would turn the button to "dark" on the iPhone.
```
led_on.value.bool_value = false;
homekit_characteristic_notify(&led_on, switch_on.value);
```

@renssies  thanks, I am not a developer, and for sure not an apple dev. but I will try to find a way to log-in to that apple's developer site.

**Comment by renssies** [comment]
Correct, that will send out a notification to the iOS device if it's currently monitoring. 

As for the developer account: You can just log in with your normal Apple ID, after accepting some terms it will be activated as a developer account as well :)

**Comment by supersjimmie** [comment]
I'm still a bit stuck on the part for turning off the button on the app.
I use the following pieces:
```
homekit_characteristic_t dim1 = HOMEKIT_CHARACTERISTIC_(
    ON, false, .callback=HOMEKIT_CHARACTERISTIC_CALLBACK(dim1_callback)
);
```
This characteristic is added to the button, which works as expected.
The ```dim1_callback``` function sends the http request, that goes fine.
After sending the http request, the following code runs:
```
	vTaskDelay(3000 / portTICK_PERIOD_MS);
	value.bool_value = false;
	homekit_characteristic_notify(&dim1, value);
```
So it should take about 3 sec and then the notify should be executed.
But nothing happens: in the log I only see the notify from the actual button-press (that has either true or false inside).
In fact, the logs shows exact the same as for a different button without the delay+notify.

**Comment by supersjimmie** [comment]
You are right @maximkulkin , there was a mistake somewhere else.
I think I have fixed that, but the result is not what I expected. Perhaps you can help me?

The code:
```
#include <stdio.h>
#include <espressif/esp_wifi.h>
#include <espressif/esp_sta.h>
#include <esp/uart.h>
#include <esp8266.h>
#include <FreeRTOS.h>
#include <task.h>

#include <homekit/homekit.h>
#include <homekit/characteristics.h>
#include "wifi.h"

#include "http_get.h"

static void wifi_init() {
    struct sdk_station_config wifi_config = {
        .ssid = WIFI_SSID,
        .password = WIFI_PASSWORD,
    };
    sdk_wifi_set_opmode(STATION_MODE);
    sdk_wifi_station_set_config(&wifi_config);
    sdk_wifi_station_connect();
}

void dim1_callback(homekit_characteristic_t *_ch, homekit_value_t on, void *context);

homekit_characteristic_t dim1 = HOMEKIT_CHARACTERISTIC_(
    ON, false, .callback=HOMEKIT_CHARACTERISTIC_CALLBACK(dim1_callback)
);

void dim1_write() {
	http_get_task("?tx433=15286568");
	vTaskDelay(3000 / portTICK_PERIOD_MS);
	homekit_value_t value;
	value.bool_value = false;
	homekit_characteristic_notify(&dim1, value);
}

void dim1_callback(homekit_characteristic_t *_ch, homekit_value_t on, void *context) {
	dim1_write();
}

void dim_init() {
}

void dim_identify_task(void *_args) {
	// no identify possible
    vTaskDelete(NULL);
}

void dim_identify(homekit_value_t _value) {
    printf("dimmer identify\n");
    xTaskCreate(dim_identify_task, "dim identify", 128, NULL, 2, NULL);
}


homekit_accessory_t *accessories[] = {
    HOMEKIT_ACCESSORY(.id=1, .category=homekit_accessory_category_switch, .services=(homekit_service_t*[]){
        HOMEKIT_SERVICE(ACCESSORY_INFORMATION, .characteristics=(homekit_characteristic_t*[]){
            HOMEKIT_CHARACTERISTIC(NAME, "Dimmer"),
            HOMEKIT_CHARACTERISTIC(MANUFACTURER, "HaPK"),
            HOMEKIT_CHARACTERISTIC(SERIAL_NUMBER, "037A2BABF19D"),
            HOMEKIT_CHARACTERISTIC(MODEL, "supersjimmie"),
            HOMEKIT_CHARACTERISTIC(FIRMWARE_REVISION, "0.1"),
            HOMEKIT_CHARACTERISTIC(IDENTIFY, dim_identify),
            NULL
        }),
        HOMEKIT_SERVICE(SWITCH, .primary=true, .characteristics=(homekit_characteristic_t*[]){
            HOMEKIT_CHARACTERISTIC(NAME, "dimbtn1"),
			&dim1,
			NULL
        }),
        NULL
    }),

    NULL
};

homekit_server_config_t config = {
    .accessories = accessories,
    .password = "111-11-111"
};

void user_init(void) {
    uart_set_baud(0, 115200);

    wifi_init();
    dim_init();
    homekit_server_init(&config);
}
```

What happens now is that, once I push the switch the system goes into a loop. It then keeps calling the http. So I guess the notify forces the callback again?

**Comment by supersjimmie** [comment]
I now have added a total of 3 buttons, each calling the same callback function. The idea is to use the same callback function for all similar buttons to prevent a lot of nearly identical functions.  Then, in that one function it would be great if I can determine from which button it was called...

I only managed to get this information visible in the callback function, by going through the ```*_ch``` var in the callback:
```
struct _homekit_characteristic {
    homekit_service_t *service;

    unsigned int id;
    const char *type;
    const char *description;
    homekit_format_t format;
    homekit_unit_t unit;
    homekit_permissions_t permissions;
    homekit_value_t value;
...
```
But none of those contain a usable value to determine which button has been pushed.
The ```id``` differs per button, but it seems to be a bit randomly assigned (three buttons are 9, 12 and 15).
The ```description``` contains "Name" for all three buttons (and ```value``` is either "true" or "false").

**Comment by maximkulkin** [comment]
@supersjimmie Yes, you should be able to deduce which button that is by inspecting data starting from a characteristic pointer provided. The easiest way in your case would be:
```c
homekit_characteristic_t *button_name = homekit_service_characteristic_by_type(
    _ch->service, HOMEKIT_CHARACTERISTIC_NAME
);
printf("button name: %s\n", button_name->value.string_value);
```

The other way to do that is to use characteristic callback context. It wasn't exposed through macros yet and I just pushed a change to enable that.
```c
// NOTICE "context" argument
void dim3_callback(homekit_characteristic_t *_ch, homekit_value_t on, void *context);

homekit_characteristic_t dim3 = HOMEKIT_CHARACTERISTIC_(
    ON, false, .callback=HOMEKIT_CHARACTERISTIC_CALLBACK(
        dim3_callback, .context=(void*)"button1"
    )
);

void dim3_callback(homekit_characteristic_t *_ch, homekit_value_t on, void *context) {
    printf("button %s callback", (char *)context);
}
```
Of course instead of just passing string as context you can pass any other type or structure pointer in case you need to pass more data.

**Comment by maximkulkin** [comment]
Regarding your code: there are a lot of inefficiencies there.
1. If you do not need identify, there is no need to start an identify task. Just wipe out `dim_identify`. The other way would be to specify NULL here: `HOMEKIT_CHARACTERISTIC(IDENTIFY, NULL)`.
2. `dim3_notify_task` is not needed, this code is not blocking and can be executed in the callback itself thus saving resources (creating tasks is expensive).
3. I'm not sure where `http_get_task()` comes from but it looks like it is already a task, there is no need to wrap it with another task.

As of reusing code for multiple buttons, when you define your characteristics, specify same callbacks, but provide different data for callback contexts.

**Comment by supersjimmie** [comment]
Thanks @maximkulkin  I'm doing all what you suggested.
Would I also be able to use that context to store the tx codes? If so, I don't need to store those apart and use a lot of ```if``` statements to find the code that belongs to a button.  :)

Seems to working, until the *context part.
To get the latest changes from your git, I do ```git submodule update --init --recursive``` which seems to do just nothing. No error, so it thinks all is fine.  (and when I check, no files are updated)

**Comment by RavenSystem** [comment]
Try this from root of repo:
`git submodule update --recursive --remote`

**Comment by maximkulkin** [comment]
Yes, submodule needs to be updated every time, but that would just result in lots of commits in demo repository. So it is updated less often and if you want to use latest and greatest, you need to update components manually either by doing `cd components/homekit && git pull origin master` or by doing `git submodule update --remote components/homekit`

**Comment by supersjimmie** [comment]
All changes seem to be working, now using that *context for the API details. :)
Next step in the process is reading data over the API calls, like temperature and humidity.
I don't think that will be difficult with what is build until now.

> I'm not sure where http_get_task() comes from but it looks like it is already a task, there is no need to wrap it with another task.

Based on this:  https://github.com/SuperHouse/esp-open-rtos/tree/master/examples/http_get
(removed the loop and some obsolete code, made it using inputs and a return value)

**Comment by supersjimmie** [comment]
I'm trying to add CO2 measurement, but somehow the "optional" part is not visible.
Is this a known issue?


```
homekit_characteristic_t co2detect    = HOMEKIT_CHARACTERISTIC_(CARBON_DIOXIDE_DETECTED, 0);
homekit_characteristic_t co2value     = HOMEKIT_CHARACTERISTIC_(CARBON_DIOXIDE_LEVEL, 0);
...
    HOMEKIT_ACCESSORY(.id=3, .category=homekit_accessory_category_sensor, .services=(homekit_service_t*[]) {
        HOMEKIT_SERVICE(ACCESSORY_INFORMATION, .characteristics=(homekit_characteristic_t*[]) {
            HOMEKIT_CHARACTERISTIC(NAME, "Sensors"),
            HOMEKIT_CHARACTERISTIC(MANUFACTURER, "HaPK"),
            HOMEKIT_CHARACTERISTIC(SERIAL_NUMBER, "0012345"),
            HOMEKIT_CHARACTERISTIC(MODEL, "Sensors"),
            HOMEKIT_CHARACTERISTIC(FIRMWARE_REVISION, "0.1"),
            HOMEKIT_CHARACTERISTIC(IDENTIFY, NULL),
            NULL
        }),
        HOMEKIT_SERVICE(CARBON_DIOXIDE_SENSOR, .characteristics=(homekit_characteristic_t*[]) {
            HOMEKIT_CHARACTERISTIC(NAME, "CO2detect"),
            &co2detect,
            &co2value,
            NULL

```

I can only see the co2detect, the co2value is missing. (a periodic ```notify``` to update the value does seem to work, it's just not showing in the app)

**Comment by supersjimmie** [comment]
I found that the value is only visible "under" the Detect button. So when I click it and look at the Details.

**Comment by maximkulkin** [comment]
I see. You can probably also reference that sensor as a trigger in automations.

**Comment by supersjimmie** [comment]
I now notice a new "glitch".
As explained, I turn the button off, right after clicking it.
But when I re-open the app on the iphone, the button is on.
This is what I see in the log at the moment I open the app (so it's a refresh):
```
>>> client_send: [Client 4] Sending payload: c5\x0D\x0A{"characteristics":[{"aid":1,"iid":10,"value":true},{"aid":1,"iid":13,"value":false},
```
That ```"value":true``` is what's wrong.
Is seems that I have to set another "value" to "false", beside doing the ```homekit_characteristic_notify(_ch, value)```?

**Comment by maximkulkin** [comment]
You should not update "name" characteristic.

As always, please send full code listing for troubleshooting. The problem might be in place you did not expect.

**Comment by supersjimmie** [comment]
Should I add this to the dim_callback?
```
		_ch->value.bool_value = false;
```

**Comment by maximkulkin** [comment]
Ok, not sure I understand what is happening in dimbtn_callback: this callback is executed when button state is changed, it gets it's new state as parameter (`on` argument). If the value is true, then you execute another notification with "false" value. Thing is that this second notification has no effect on your internal state, but changes state of controllers (iPhones). So, controllers think that the state is "false", but in reality it is "true". When you re-open Home.app, it re-reads value directly -> thus change of state.

If you want to update internal state, you need to update `_ch->value`: `_ch->value = HOEMKIT_BOOL(false);`
The other thing that will probably work better for you is: if you really need to control the value of your characteristic, instead of using notification callback you need to define custom setter (and in some cases - getter) for your characteristic.

**Comment by supersjimmie** [comment]
Yep, that ```_ch->value = HOMEKIT_BOOL(false);``` did the trick.
I don't think that the .setter (or getter) would be very useful, I can now use one function for all similar buttons (same functionality with only different properties) but with .setter I would have to create separate functions for each button.  That is because with the callback I can check from which button the function was called while the .setter doesn't have that ability. (or does it?)
