### ISSUE TITLE
Example temerature_sensor

### ISSUE THREAD

**Issue by WimVanHonacker** [maximkulkin/esp-homekit-demo#83]
Hello,
I tried to make the temerature_sensor bin file for ESP8266.
I've got an error that dht.h not erxists.
Where can i find this file?

**Comment by maximkulkin** [comment]
dht.h comes with esp-open-rtos as an extra library. You need to install esp-open-rtos and set SDK_PATH environment variable pointing to that repository checkout. See instructions in README.
