### ISSUE TITLE
ws2812_i2s/ws2812_i2s.h: No such file or directory

### ISSUE THREAD

**Issue by VihlayewAlex** [maximkulkin/esp-homekit-demo#84]
I followed instruction step by step, but in the end when trying to build I got this error:
![screen shot 2018-05-22 at 3 20 08 pm](https://user-images.githubusercontent.com/22377058/40361959-c2047684-5dd3-11e8-9938-8a2bfea72e57.png)

**Comment by maximkulkin** [comment]
Oh, yeah. It looks like the issue is: when you build ESP32 project, it tries to build every component it can reach although some components in paths are for ESP_OPEN_RTOS only. I will look into proper fix for that but in the meantime feel free to delete that WS2812FX component.

**Comment by manur84** [comment]
I have this library deletet and then this error does not come

Then ive got error espressif/espcommon.h no such file / directory 

I put esp-free-rtos directory in the include directory from mysys32 and i can flash with no problems

I use windows 10 
Sorry for my bad english
