### ISSUE TITLE
compile error when i update the esp-open-rtos

### ISSUE THREAD

**Issue by xfce** [maximkulkin/esp-homekit-demo#87]
Hi, all
today when i update the esp-open-rtos, then compile got error bellow

/home/bi4wms/projects/esp-open-sdk/esp-open-rtos//core/include/sdk_internal.h:371:16: error: 'struct pbuf' has no member named 'esf_buf'
 _Static_assert(offsetof(struct pbuf, esf_buf) == 16, "pbuf->esf_buf offset wrong!");
                ^
/home/bi4wms/projects/esp-open-sdk/esp-open-rtos//core/include/sdk_internal.h:371:16: error: expression in static assertion is not an integer
/home/bi4wms/projects/esp-open-sdk/esp-open-rtos//open_esplibs/component.mk:15: recipe for target 'build/open_esplibs_libmain//user_interface.o' failed
make: *** [build/open_esplibs_libmain//user_interface.o] Error 1
make: Leaving directory '/home/bi4wms/projects/esp-open-sdk/esp-homekit-demo/examples/button'

**Comment by RavenSystem** [comment]
Dependences has not been updated. Update your esp-open-rtos repo with this:
`git submodule update --recursive --remote`

**Comment by xfce** [comment]
it's ok, thanks
