### ISSUE TITLE
magic_home stripe

### ISSUE THREAD

**Issue by Kristian8606** [maximkulkin/esp-homekit-demo#92]
Hello I want to share about the problems I see on magic_home stripe.
The ESP module heats up more than normal, when setting the colors, flickering is noticeable, when it works longer, the light diminishes as if it is 30% and is fixed after a restart.
Has anyone noticed this behavior or I have a hardware problem?

**Comment by pcsaito** [comment]
I am noticing some strange behavior with the pwm too.

Actually looking for a better pwm routines with 3 simultaneous channels.

**Comment by maximkulkin** [comment]
What is the wiring in your case? Do you have external power of LEDs?

**Comment by Kristian8606** [comment]
magic home controller burned I used its transistors and built a new esp controller. the new controller also heated and he also burned. I have a third controller that worked for a year with a home bridge but now it also heats up strongly with this code but still works. Strip e 4 meters 5050

**Comment by Kristian8606** [comment]
The LED bar has an external power supply

**Comment by xfce** [comment]
Does the firmware only support RGB, not RGBW? Thanks

**Comment by Kristian8606** [comment]
The firmware supports RGB

**Comment by xfce** [comment]
Is there some reference for RGBW use this code? Thanks

**Comment by maccoylton** [comment]
I created an RGBW with OTA firmware with can be found here:- 

https://github.com/maccoylton/esp-homekit-rgbw-strip

NOTE I would NOT recommend using this code at this time. I believe my module may also burned out, after a few weeks. In the process of checking that's the issue.

**Comment by surya31** [comment]
can you tell me how to connect led strip to nodemcu?? i am stuck at the wiring part

**Comment by pcsaito** [comment]
@surya31 You can use this guide for the wirings:
https://github.com/arendst/Sonoff-Tasmota/wiki/MagicHome-LED-strip-controller

**Comment by tybkyb** [comment]
Hello, if I wanna use a SMD 5050 led, do I have to take a MagicHome controller or is it easy to do with the led strip demo which is made for ws2812? Hope you can give me some advice.

**Comment by maximkulkin** [comment]
@tybkyb SMD 5050 is a generic name for a surface mount components which have 5x5mm dimensions and which is ciommonly used to refer to LEDs.
WS2812 on the other hand is particular LED.

Which one to use depends on yor needs (e.g sizes, power consumption, brightness required). I can not say for any LED you can find, but I believe for majority of them you can find a library.
