### ISSUE TITLE
Can this project build on ESP8266_RTOS_SDK?

### ISSUE THREAD

**Issue by whlsxl** [maximkulkin/esp-homekit-demo#93]
Can this build on the official sdk [ESP8266_RTOS_SDK](https://github.com/espressif/ESP8266_RTOS_SDK)?

**Comment by renssies** [comment]
No, this is not possible due to the official SDK using some outdated components

**Comment by whlsxl** [comment]
@renssies [ESP8266_RTOS_SDK](https://github.com/espressif/ESP8266_RTOS_SDK) had upgrade to very recently [version](https://github.com/espressif/ESP8266_RTOS_SDK/blob/master/components/VERSION.md)

**Comment by ziolelle** [comment]
+1 for build on ESP8266_RTOS_SDK
