### ISSUE TITLE
Question: Any plans to implement OTA updates?

### ISSUE THREAD

**Issue by peros550** [maximkulkin/esp-homekit-demo#97]
Hi, 

I never had the chance, so I would like to thank everybody who with their efforts made this project a reality. 

I was wondering if there are any plans to create an OTA functionality for future updates.

Thanks & Regards

**Comment by maximkulkin** [comment]
@HomeACcessoryKid is working on it. I'll leave it to him to explain the progress.

**Comment by maccoylton** [comment]
I've been doing some testing and created a few examples based on the work @HomeACcessoryKid has done, a little more work to do on instruction, but I have these up and running across 5 devices.

https://github.com/maccoylton/esp-homekit-sonoff-basic
https://github.com/maccoylton/esp-homekit-sonoff-s20
https://github.com/maccoylton/homekit_wifi_thermostat

**Comment by kiralikbeyin** [comment]
@maccoylton do you have any updated repo?

**Comment by kiralikbeyin** [comment]
please check #245
